// Generate by scrape_groups.py
import { Symbol } from "./symbol";

import { Item } from "./item";

export enum Group {
  Gem = "gem",
  Scaler = "scaler",
  Poslikes = "poslikes",
  Piratelikes = "piratelikes",
  Plant = "plant",
  Food = "food",
  Fruit = "fruit",
  Witchlikes = "witchlikes",
  Farmerlikes = "farmerlikes",
  Robinhates = "robinhates",
  Organism = "organism",
  Human = "human",
  Doglikes = "doglikes",
  Monkeylikes = "monkeylikes",
  Fruitlikes = "fruitlikes",
  Funny = "funny",
  Spawner0 = "spawner0",
  Darkhumor = "darkhumor",
  Triggerchance = "triggerchance",
  Animal = "animal",
  Beelikes = "beelikes",
  Booze = "booze",
  Dwarflikes = "dwarflikes",
  Anvillikes = "anvillikes",
  Minerlikes = "minerlikes",
  Archlikes = "archlikes",
  Ore = "ore",
  Kyle = "kyle",
  Spiritbox = "spiritbox",
  Box = "box",
  Arrow = "arrow",
  Robinlikes = "robinlikes",
  Toddlerlikes = "toddlerlikes",
  Capsule = "capsule",
  Halloween = "halloween",
  Counted = "counted",
  Raritymod = "raritymod",
  Omelettestuff = "omelettestuff",
  Richlikes = "richlikes",
  Bird = "bird",
  Chickenstuff = "chickenstuff",
  Spawner1 = "spawner1",
  Suit = "suit",
  Time_machine = "time_machine",
  Fossillikes = "fossillikes",
  Eachother = "eachother",
  Time_machine3 = "time_machine3",
  Destroyable_matryoshka = "destroyable_matryoshka",
  Hex = "hex",
  Triggerhex = "triggerhex",
  Chest = "chest",
  Slow = "slow",
  Night = "night",
  Time_capsule_effects = "time_capsule_effects",
  Void = "void",
  Pepper = "pepper",
}

export function isGroup(s: string): boolean {
  return Object.values(Group).includes(s as any);
}

export const GROUP_MEMBERS: Record<Group, Array<Symbol | Item>> = {
  [Group.Gem]: [
    Symbol.Amethyst,
    Symbol.Diamond,
    Symbol.Emerald,
    Symbol.Pearl,
    Symbol.Ruby,
    Symbol.Sapphire,
    Symbol.ShinyPebble,
    Symbol.VoidStone,
  ],
  [Group.Scaler]: [
    Symbol.Amethyst,
    Symbol.Geologist,
    Symbol.Diver,
    Symbol.Dove,
    Symbol.MrsFruit,
    Symbol.Pear,
    Symbol.Pirate,
  ],
  [Group.Poslikes]: [
    Symbol.Anchor,
    Symbol.Crab,
    Symbol.Goldfish,
    Symbol.Jellyfish,
    Symbol.Oyster,
    Symbol.Pearl,
    Symbol.Pufferfish,
    Symbol.SandDollar,
    Symbol.Snail,
    Symbol.Turtle,
  ],
  [Group.Piratelikes]: [
    Symbol.Anchor,
    Symbol.Beer,
    Symbol.Coin,
    Symbol.Lockbox,
    Symbol.MegaChest,
    Symbol.Orange,
    Symbol.Safe,
    Symbol.TreasureChest,
  ],
  [Group.Plant]: [
    Symbol.Apple,
    Symbol.Banana,
    Symbol.Cherry,
    Symbol.Coconut,
    Symbol.Flower,
    Symbol.Orange,
    Symbol.Peach,
    Symbol.Pear,
    Symbol.Strawberry,
    Symbol.VoidFruit,
    Symbol.Watermelon,
  ],
  [Group.Food]: [
    Symbol.Apple,
    Symbol.Banana,
    Symbol.Beer,
    Symbol.Candy,
    Symbol.Cheese,
    Symbol.ChemicalSeven,
    Symbol.Cherry,
    Symbol.CoconutHalf,
    Symbol.Egg,
    Symbol.GoldenEgg,
    Symbol.Honey,
    Symbol.Martini,
    Symbol.Milk,
    Symbol.Omelette,
    Symbol.Orange,
    Symbol.Peach,
    Symbol.Pear,
    Symbol.Strawberry,
    Symbol.VoidFruit,
    Symbol.Watermelon,
    Symbol.Wine,
  ],
  [Group.Fruit]: [
    Symbol.Apple,
    Symbol.Banana,
    Symbol.Cherry,
    Symbol.Coconut,
    Symbol.CoconutHalf,
    Symbol.Orange,
    Symbol.Peach,
    Symbol.Pear,
    Symbol.Strawberry,
    Symbol.VoidFruit,
    Symbol.Watermelon,
  ],
  [Group.Witchlikes]: [
    Symbol.Apple,
    Symbol.Cat,
    Symbol.Crow,
    Symbol.EldritchCreature,
    Symbol.HexOfDestruction,
    Symbol.HexOfDraining,
    Symbol.HexOfEmptiness,
    Symbol.HexOfHoarding,
    Symbol.HexOfMidas,
    Symbol.HexOfTedium,
    Symbol.HexOfThievery,
    Symbol.Owl,
    Symbol.Spirit,
  ],
  [Group.Farmerlikes]: [
    Symbol.Apple,
    Symbol.Banana,
    Symbol.Cheese,
    Symbol.Cherry,
    Symbol.Chick,
    Symbol.Chicken,
    Symbol.Coconut,
    Symbol.Cow,
    Symbol.Egg,
    Symbol.Flower,
    Symbol.GoldenEgg,
    Symbol.Milk,
    Symbol.Orange,
    Symbol.Peach,
    Symbol.Pear,
    Symbol.Seed,
    Symbol.Strawberry,
    Symbol.VoidFruit,
    Symbol.Watermelon,
  ],
  [Group.Robinhates]: [Symbol.Apple, Symbol.Billionaire, Symbol.Target],
  [Group.Organism]: [
    Symbol.Geologist,
    Symbol.Bartender,
    Symbol.Bear,
    Symbol.Beastmaster,
    Symbol.Bee,
    Symbol.BountyHunter,
    Symbol.CardShark,
    Symbol.Cat,
    Symbol.Chef,
    Symbol.Chick,
    Symbol.Chicken,
    Symbol.Comedian,
    Symbol.Cow,
    Symbol.Crab,
    Symbol.Crow,
    Symbol.Cultist,
    Symbol.Dame,
    Symbol.Diver,
    Symbol.Dog,
    Symbol.Dove,
    Symbol.Dwarf,
    Symbol.EldritchCreature,
    Symbol.Farmer,
    Symbol.Gambler,
    Symbol.GeneralZaroff,
    Symbol.Goldfish,
    Symbol.Golem,
    Symbol.Goose,
    Symbol.Hooligan,
    Symbol.Jellyfish,
    Symbol.Joker,
    Symbol.KingMidas,
    Symbol.Magpie,
    Symbol.Miner,
    Symbol.Monkey,
    Symbol.Mouse,
    Symbol.MrsFruit,
    Symbol.Ninja,
    Symbol.Owl,
    Symbol.Oyster,
    Symbol.Pirate,
    Symbol.Pufferfish,
    Symbol.Rabbit,
    Symbol.RobinHood,
    Symbol.SandDollar,
    Symbol.Sloth,
    Symbol.Snail,
    Symbol.Thief,
    Symbol.Toddler,
    Symbol.Turtle,
    Symbol.VoidCreature,
    Symbol.Witch,
    Symbol.Wolf,
  ],
  [Group.Human]: [
    Symbol.Geologist,
    Symbol.Bartender,
    Symbol.Beastmaster,
    Symbol.Billionaire,
    Symbol.BountyHunter,
    Symbol.CardShark,
    Symbol.Chef,
    Symbol.Comedian,
    Symbol.Cultist,
    Symbol.Dame,
    Symbol.Diver,
    Symbol.Dwarf,
    Symbol.Farmer,
    Symbol.Gambler,
    Symbol.GeneralZaroff,
    Symbol.Hooligan,
    Symbol.Joker,
    Symbol.KingMidas,
    Symbol.Miner,
    Symbol.MrsFruit,
    Symbol.Ninja,
    Symbol.Pirate,
    Symbol.RobinHood,
    Symbol.Thief,
    Symbol.Toddler,
    Symbol.Witch,
  ],
  [Group.Doglikes]: [
    Symbol.Geologist,
    Symbol.Bartender,
    Symbol.Beastmaster,
    Symbol.BountyHunter,
    Symbol.CardShark,
    Symbol.Chef,
    Symbol.Comedian,
    Symbol.Cultist,
    Symbol.Dame,
    Symbol.Diver,
    Symbol.Dwarf,
    Symbol.Farmer,
    Symbol.Gambler,
    Symbol.GeneralZaroff,
    Symbol.Hooligan,
    Symbol.Joker,
    Symbol.KingMidas,
    Symbol.Miner,
    Symbol.MrsFruit,
    Symbol.Ninja,
    Symbol.Pirate,
    Symbol.RobinHood,
    Symbol.Thief,
    Symbol.Toddler,
    Symbol.Witch,
  ],
  [Group.Monkeylikes]: [Symbol.Banana, Symbol.Coconut, Symbol.CoconutHalf],
  [Group.Fruitlikes]: [
    Symbol.Banana,
    Symbol.Cherry,
    Symbol.Coconut,
    Symbol.CoconutHalf,
    Symbol.Orange,
    Symbol.Peach,
  ],
  [Group.Funny]: [
    Symbol.Banana,
    Symbol.BananaPeel,
    Symbol.Dog,
    Symbol.Joker,
    Symbol.Monkey,
    Symbol.Toddler,
  ],
  [Group.Spawner0]: [
    Symbol.Bartender,
    Symbol.Beehive,
    Symbol.Chicken,
    Symbol.Cow,
    Symbol.Goose,
    Symbol.HexOfMidas,
    Symbol.Oyster,
    Symbol.Rabbit,
    Symbol.Tomb,
  ],
  [Group.Darkhumor]: [
    Symbol.Bartender,
    Symbol.Beer,
    Symbol.BigUrn,
    Symbol.Spirit,
    Symbol.Tomb,
    Symbol.Urn,
    Symbol.Wine,
  ],
  [Group.Triggerchance]: [
    Symbol.Bartender,
    Symbol.Beehive,
    Symbol.Chick,
    Symbol.Chicken,
    Symbol.Cow,
    Symbol.Egg,
    Symbol.Goose,
    Symbol.Oyster,
    Symbol.Tomb,
  ],
  [Group.Animal]: [
    Symbol.Bear,
    Symbol.Bee,
    Symbol.Cat,
    Symbol.Chick,
    Symbol.Chicken,
    Symbol.Cow,
    Symbol.Crab,
    Symbol.Crow,
    Symbol.Dog,
    Symbol.Dove,
    Symbol.EldritchCreature,
    Symbol.Goldfish,
    Symbol.Goose,
    Symbol.Jellyfish,
    Symbol.Magpie,
    Symbol.Monkey,
    Symbol.Mouse,
    Symbol.Owl,
    Symbol.Oyster,
    Symbol.Pufferfish,
    Symbol.Rabbit,
    Symbol.SandDollar,
    Symbol.Sloth,
    Symbol.Snail,
    Symbol.Turtle,
    Symbol.VoidCreature,
    Symbol.Wolf,
  ],
  [Group.Beelikes]: [Symbol.Beehive, Symbol.Flower, Symbol.Honey],
  [Group.Booze]: [
    Symbol.Beer,
    Symbol.ChemicalSeven,
    Symbol.Martini,
    Symbol.Wine,
  ],
  [Group.Dwarflikes]: [Symbol.Beer, Symbol.Wine],
  [Group.Anvillikes]: [Symbol.Beer, Symbol.BigOre, Symbol.Ore, Symbol.Wine],
  [Group.Minerlikes]: [Symbol.BigOre, Symbol.Ore],
  [Group.Archlikes]: [
    Symbol.BigOre,
    Symbol.Ore,
    Symbol.Pearl,
    Symbol.Sapphire,
    Symbol.ShinyPebble,
  ],
  [Group.Ore]: [Symbol.BigOre, Symbol.Ore],
  [Group.Kyle]: [Symbol.BigOre, Symbol.Ore, Symbol.ShinyPebble],
  [Group.Spiritbox]: [Symbol.BigUrn, Symbol.Tomb, Symbol.Urn],
  [Group.Box]: [
    Symbol.Billionaire,
    Symbol.ChemicalSeven,
    Symbol.Gambler,
    Symbol.Lockbox,
    Symbol.LuckyCapsule,
    Symbol.MegaChest,
    Symbol.Present,
    Symbol.Safe,
    Symbol.Target,
    Symbol.TediumCapsule,
    Symbol.Thief,
    Symbol.TreasureChest,
    Symbol.VoidCreature,
    Symbol.VoidFruit,
    Symbol.VoidStone,
  ],
  [Group.Arrow]: [Symbol.BronzeArrow, Symbol.GoldenArrow, Symbol.SilverArrow],
  [Group.Robinlikes]: [
    Symbol.BronzeArrow,
    Symbol.GoldenArrow,
    Symbol.SilverArrow,
    Symbol.Thief,
  ],
  [Group.Toddlerlikes]: [
    Symbol.Bubble,
    Symbol.Candy,
    Symbol.Pinata,
    Symbol.Present,
  ],
  [Group.Capsule]: [
    Symbol.BuffingCapsule,
    Symbol.EssenceCapsule,
    Symbol.Gambler,
    Symbol.ItemCapsule,
    Symbol.LuckyCapsule,
    Symbol.WealthyCapsule,
    Symbol.RemovalCapsule,
    Symbol.RerollCapsule,
    Symbol.TediumCapsule,
    Symbol.TimeCapsule,
  ],
  [Group.Halloween]: [Symbol.Candy, Symbol.Toddler],
  [Group.Counted]: [
    Symbol.Candy,
    Symbol.Clubs,
    Symbol.Cultist,
    Symbol.Diamond,
    Symbol.Diamonds,
    Symbol.Emerald,
    Symbol.Hearts,
    Symbol.Ninja,
    Symbol.Ruby,
    Symbol.Spades,
    Symbol.Spirit,
    Symbol.Strawberry,
    Symbol.Watermelon,
  ],
  [Group.Raritymod]: [
    Symbol.Cat,
    Symbol.HexOfTedium,
    Symbol.RabbitFluff,
    Symbol.ShinyPebble,
  ],
  [Group.Omelettestuff]: [
    Symbol.Cheese,
    Symbol.Egg,
    Symbol.GoldenEgg,
    Symbol.Milk,
    Symbol.Omelette,
  ],
  [Group.Richlikes]: [Symbol.Cheese, Symbol.Wine],
  [Group.Bird]: [
    Symbol.Chick,
    Symbol.Chicken,
    Symbol.Crow,
    Symbol.Dove,
    Symbol.Goose,
    Symbol.Magpie,
    Symbol.Owl,
  ],
  [Group.Chickenstuff]: [
    Symbol.Chick,
    Symbol.Chicken,
    Symbol.Egg,
    Symbol.GoldenEgg,
  ],
  [Group.Spawner1]: [Symbol.Chicken],
  [Group.Suit]: [Symbol.Clubs, Symbol.Diamonds, Symbol.Hearts, Symbol.Spades],
  [Group.Time_machine]: [
    Symbol.Coal,
    Symbol.FrozenFossil,
    Symbol.Golem,
    Symbol.MatryoshkaDoll1,
    Symbol.MatryoshkaDoll2,
    Symbol.MatryoshkaDoll3,
    Symbol.MatryoshkaDoll4,
    Symbol.Present,
  ],
  [Group.Fossillikes]: [
    Symbol.Cultist,
    Symbol.HexOfDestruction,
    Symbol.HexOfDraining,
    Symbol.HexOfEmptiness,
    Symbol.HexOfHoarding,
    Symbol.HexOfMidas,
    Symbol.HexOfTedium,
    Symbol.HexOfThievery,
    Symbol.Witch,
  ],
  [Group.Eachother]: [
    Symbol.Cultist,
    Symbol.Diamond,
    Symbol.Ninja,
    Symbol.Watermelon,
  ],
  [Group.Time_machine3]: [Symbol.FrozenFossil, Symbol.Present],
  [Group.Destroyable_matryoshka]: [
    Symbol.Golem,
    Symbol.MatryoshkaDoll1,
    Symbol.MatryoshkaDoll2,
    Symbol.MatryoshkaDoll3,
    Symbol.MatryoshkaDoll4,
  ],
  [Group.Hex]: [
    Symbol.HexOfDestruction,
    Symbol.HexOfDraining,
    Symbol.HexOfEmptiness,
    Symbol.HexOfHoarding,
    Symbol.HexOfMidas,
    Symbol.HexOfTedium,
    Symbol.HexOfThievery,
  ],
  [Group.Triggerhex]: [
    Symbol.HexOfDestruction,
    Symbol.HexOfDraining,
    Symbol.HexOfEmptiness,
    Symbol.HexOfHoarding,
    Symbol.HexOfMidas,
    Symbol.HexOfThievery,
  ],
  [Group.Chest]: [
    Symbol.Lockbox,
    Symbol.MegaChest,
    Symbol.Safe,
    Symbol.TreasureChest,
  ],
  [Group.Slow]: [
    Symbol.Magpie,
    Symbol.Owl,
    Symbol.RobinHood,
    Symbol.Sloth,
    Symbol.Snail,
    Symbol.Turtle,
  ],
  [Group.Night]: [Symbol.Owl, Symbol.Rabbit, Symbol.Wolf],
  [Group.Time_capsule_effects]: [Symbol.TimeCapsule],
  [Group.Void]: [Symbol.VoidCreature, Symbol.VoidFruit, Symbol.VoidStone],
  [Group.Pepper]: [
    Item.YellowPepper,
    Item.WhitePepper,
    Item.RedPepper,
    Item.PurplePepper,
    Item.PinkPepper,
    Item.LimePepper,
    Item.GreenPepper,
    Item.GrayPepper,
    Item.CyanPepper,
    Item.BrownPepper,
    Item.BluePepper,
    Item.BlackPepper,
  ],
};
