import { Rarity } from "./rarity"

export enum Symbol {
    Amethyst = "Amethyst",
    Anchor = "Anchor",
    Apple = "Apple",
    Banana = "Banana",
    BananaPeel = "BananaPeel",
    BarofSoap = "BarofSoap",
    Bartender = "Bartender",
    Bear = "Bear",
    Beastmaster = "Beastmaster",
    Bee = "Bee",
    Beehive = "Beehive",
    Beer = "Beer",
    BigOre = "BigOre",
    BigUrn = "BigUrn",
    Billionaire = "Billionaire",
    BountyHunter = "BountyHunter",
    BronzeArrow = "BronzeArrow",
    Bubble = "Bubble",
    BuffingCapsule = "BuffingCapsule",
    Candy = "Candy",
    CardShark = "CardShark",
    Cat = "Cat",
    Cheese = "Cheese",
    Chef = "Chef",
    ChemicalSeven = "ChemicalSeven",
    Cherry = "Cherry",
    Chick = "Chick",
    Chicken = "Chicken",
    Clubs = "Clubs",
    Coal = "Coal",
    Coconut = "Coconut",
    CoconutHalf = "CoconutHalf",
    Coin = "Coin",
    Comedian = "Comedian",
    Cow = "Cow",
    Crab = "Crab",
    Crow = "Crow",
    Cultist = "Cultist",
    Dame = "Dame",
    Diamond = "Diamond",
    Diamonds = "Diamonds",
    Diver = "Diver",
    Dog = "Dog",
    Dove = "Dove",
    Dud = "Dud",
    Dwarf = "Dwarf",
    Egg = "Egg",
    EldritchCreature = "EldritchCreature",
    Emerald = "Emerald",
    Empty = "Empty",
    EssenceCapsule = "EssenceCapsule",
    Farmer = "Farmer",
    FiveSidedDie = "FiveSidedDie",
    Flower = "Flower",
    FrozenFossil = "FrozenFossil",
    Gambler = "Gambler",
    GeneralZaroff = "GeneralZaroff",
    Geologist = "Geologist",
    GoldenArrow = "GoldenArrow",
    GoldenEgg = "GoldenEgg",
    Goldfish = "Goldfish",
    Golem = "Golem",
    Goose = "Goose",
    Hearts = "Hearts",
    HexOfDestruction = "HexOfDestruction",
    HexOfDraining = "HexOfDraining",
    HexOfEmptiness = "HexOfEmptiness",
    HexOfHoarding = "HexOfHoarding",
    HexOfMidas = "HexOfMidas",
    HexOfTedium = "HexOfTedium",
    HexOfThievery = "HexOfThievery",
    Highlander = "Highlander",
    Honey = "Honey",
    Hooligan = "Hooligan",
    HustlingCapsule = "HustlingCapsule",
    ItemCapsule = "ItemCapsule",
    Jellyfish = "Jellyfish",
    Joker = "Joker",
    Key = "Key",
    KingMidas = "KingMidas",
    LightBulb = "LightBulb",
    Lockbox = "Lockbox",
    LuckyCapsule = "LuckyCapsule",
    MagicKey = "MagicKey",
    Magpie = "Magpie",
    Martini = "Martini",
    MatryoshkaDoll1 = "MatryoshkaDoll1",
    MatryoshkaDoll2 = "MatryoshkaDoll2",
    MatryoshkaDoll3 = "MatryoshkaDoll3",
    MatryoshkaDoll4 = "MatryoshkaDoll4",
    MatryoshkaDoll5 = "MatryoshkaDoll5",
    MegaChest = "MegaChest",
    MidasBomb = "MidasBomb",
    Milk = "Milk",
    Mine = "Mine",
    Miner = "Miner",
    Monkey = "Monkey",
    Moon = "Moon",
    Mouse = "Mouse",
    MrsFruit = "MrsFruit",
    Ninja = "Ninja",
    Omelette = "Omelette",
    Orange = "Orange",
    Ore = "Ore",
    Owl = "Owl",
    Oyster = "Oyster",
    Peach = "Peach",
    Pear = "Pear",
    Pearl = "Pearl",
    Pirate = "Pirate",
    Pinata = "Pinata",
    Plum = "Plum",
    Present = "Present",
    Pufferfish = "Pufferfish",
    Rabbit = "Rabbit",
    RabbitFluff = "RabbitFluff",
    Rain = "Rain",
    RemovalCapsule = "RemovalCapsule",
    RerollCapsule = "RerollCapsule",
    RobinHood = "RobinHood",
    Ruby = "Ruby",
    Safe = "Safe",
    SandDollar = "SandDollar",
    Sapphire = "Sapphire",
    Seed = "Seed",
    ShinyPebble = "ShinyPebble",
    SilverArrow = "SilverArrow",
    Sloth = "Sloth",
    Snail = "Snail",
    Spades = "Spades",
    Spirit = "Spirit",
    Strawberry = "Strawberry",
    Sun = "Sun",
    Target = "Target",
    TediumCapsule = "TediumCapsule",
    Thief = "Thief",
    ThreeSidedDie = "ThreeSidedDie",
    TimeCapsule = "TimeCapsule",
    Toddler = "Toddler",
    Tomb = "Tomb",
    TreasureChest = "TreasureChest",
    Turtle = "Turtle",
    Urn = "Urn",
    VoidCreature = "VoidCreature",
    VoidFruit = "VoidFruit",
    VoidStone = "VoidStone",
    Watermelon = "Watermelon",
    WealthyCapsule = "WealthyCapsule",
    Wildcard = "Wildcard",
    Wine = "Wine",
    Witch = "Witch",
    Wolf = "Wolf",
    Unknown = "Unknown",
}

export function isSymbol(s: string): s is Symbol {
    return Object.values(Symbol).includes(s as any);
}

export namespace SymbolUtils {
    export function isArrow(s: Symbol): boolean {
        return [Symbol.BronzeArrow, Symbol.SilverArrow, Symbol.GoldenArrow].includes(s);
    }

    export function isEater(s: Symbol): boolean {
        return [Symbol.Geologist, Symbol.Diver, Symbol.MrsFruit, Symbol.EldritchCreature, Symbol.Pirate].includes(s);
    }

    export function isGrower(s: Symbol): boolean {
        return [Symbol.Amethyst, Symbol.Pear, Symbol.Dove].includes(s);
    }

    export function symbolToDisplay(s: Symbol): string {
        let upperCased = s.replace(/([A-Z][a-z])/g, " $1").trim();
        let titleCased = upperCased.split(" ").map((s) => {
            switch (s) {
                case "The":
                    return "the";
                case "On":
                    return "on";
                case "Of":
                    return "of";
                case "A":
                    return "a";
                case "And":
                    return "and";
                default:
                    return s;
            }
        }).join(" ");


        switch (titleCased) {
            case "Barof Soap":
                titleCased = "Bar of Soap";
                break;
            case "Five Sided Die":
                titleCased = "Five-Sided Die";
                break;
            case "Mrs Fruit":
                titleCased = "Mrs. Fruit";
                break;
            case "Three Sided Die":
                titleCased = "Three-Sided Die";
                break;
        }

        return titleCased;
    }
}

export const SYMBOL_RARITIES: Record<Symbol, Rarity> = {
    [Symbol.Amethyst]: Rarity.Rare,
    [Symbol.Anchor]: Rarity.Common,
    [Symbol.Apple]: Rarity.Rare,
    [Symbol.Banana]: Rarity.Common,
    [Symbol.BananaPeel]: Rarity.Common,
    [Symbol.BarofSoap]: Rarity.Uncommon,
    [Symbol.Bartender]: Rarity.Rare,
    [Symbol.Bear]: Rarity.Uncommon,
    [Symbol.Beastmaster]: Rarity.Rare,
    [Symbol.Bee]: Rarity.Common,
    [Symbol.Beehive]: Rarity.Rare,
    [Symbol.Beer]: Rarity.Common,
    [Symbol.BigOre]: Rarity.Uncommon,
    [Symbol.BigUrn]: Rarity.Uncommon,
    [Symbol.Billionaire]: Rarity.Uncommon,
    [Symbol.BountyHunter]: Rarity.Common,
    [Symbol.BronzeArrow]: Rarity.Uncommon,
    [Symbol.Bubble]: Rarity.Common,
    [Symbol.BuffingCapsule]: Rarity.Uncommon,
    [Symbol.Candy]: Rarity.Common,
    [Symbol.CardShark]: Rarity.Rare,
    [Symbol.Cat]: Rarity.Common,
    [Symbol.Cheese]: Rarity.Common,
    [Symbol.Chef]: Rarity.Rare,
    [Symbol.ChemicalSeven]: Rarity.Uncommon,
    [Symbol.Cherry]: Rarity.Common,
    [Symbol.Chick]: Rarity.Uncommon,
    [Symbol.Chicken]: Rarity.Rare,
    [Symbol.Clubs]: Rarity.Uncommon,
    [Symbol.Coal]: Rarity.Common,
    [Symbol.Coconut]: Rarity.Uncommon,
    [Symbol.CoconutHalf]: Rarity.Uncommon,
    [Symbol.Coin]: Rarity.Common,
    [Symbol.Comedian]: Rarity.Rare,
    [Symbol.Cow]: Rarity.Rare,
    [Symbol.Crab]: Rarity.Common,
    [Symbol.Crow]: Rarity.Common,
    [Symbol.Cultist]: Rarity.Common,
    [Symbol.Dame]: Rarity.Rare,
    [Symbol.Diamond]: Rarity.VeryRare,
    [Symbol.Diamonds]: Rarity.Uncommon,
    [Symbol.Diver]: Rarity.Rare,
    [Symbol.Dog]: Rarity.Common,
    [Symbol.Dove]: Rarity.Rare,
    [Symbol.Dud]: Rarity.Special,
    [Symbol.Dwarf]: Rarity.Common,
    [Symbol.Egg]: Rarity.Common,
    [Symbol.EldritchCreature]: Rarity.VeryRare,
    [Symbol.Emerald]: Rarity.Rare,
    [Symbol.Empty]: Rarity.Special,
    [Symbol.EssenceCapsule]: Rarity.Uncommon,
    [Symbol.Farmer]: Rarity.Rare,
    [Symbol.FiveSidedDie]: Rarity.Uncommon,
    [Symbol.Flower]: Rarity.Common,
    [Symbol.FrozenFossil]: Rarity.Rare,
    [Symbol.Gambler]: Rarity.Common,
    [Symbol.GeneralZaroff]: Rarity.Rare,
    [Symbol.Geologist]: Rarity.Rare,
    [Symbol.GoldenArrow]: Rarity.VeryRare,
    [Symbol.GoldenEgg]: Rarity.Rare,
    [Symbol.Goldfish]: Rarity.Common,
    [Symbol.Golem]: Rarity.Uncommon,
    [Symbol.Goose]: Rarity.Common,
    [Symbol.Hearts]: Rarity.Uncommon,
    [Symbol.HexOfDestruction]: Rarity.Uncommon,
    [Symbol.HexOfDraining]: Rarity.Uncommon,
    [Symbol.HexOfEmptiness]: Rarity.Uncommon,
    [Symbol.HexOfHoarding]: Rarity.Uncommon,
    [Symbol.HexOfMidas]: Rarity.Uncommon,
    [Symbol.HexOfTedium]: Rarity.Uncommon,
    [Symbol.HexOfThievery]: Rarity.Uncommon,
    [Symbol.Highlander]: Rarity.VeryRare,
    [Symbol.Honey]: Rarity.Rare,
    [Symbol.Hooligan]: Rarity.Uncommon,
    [Symbol.HustlingCapsule]: Rarity.Uncommon,
    [Symbol.ItemCapsule]: Rarity.Uncommon,
    [Symbol.Jellyfish]: Rarity.Uncommon,
    [Symbol.Joker]: Rarity.Rare,
    [Symbol.Key]: Rarity.Common,
    [Symbol.KingMidas]: Rarity.Rare,
    [Symbol.LightBulb]: Rarity.Common,
    [Symbol.Lockbox]: Rarity.Common,
    [Symbol.LuckyCapsule]: Rarity.Uncommon,
    [Symbol.MagicKey]: Rarity.Rare,
    [Symbol.Magpie]: Rarity.Common,
    [Symbol.Martini]: Rarity.Rare,
    [Symbol.MatryoshkaDoll1]: Rarity.Uncommon,
    // TODO: Should this just be uncommon? After all, the base symbol is uncommon
    [Symbol.MatryoshkaDoll2]: Rarity.Special,
    [Symbol.MatryoshkaDoll3]: Rarity.Special,
    [Symbol.MatryoshkaDoll4]: Rarity.Special,
    [Symbol.MatryoshkaDoll5]: Rarity.Special,
    [Symbol.MegaChest]: Rarity.VeryRare,
    [Symbol.MidasBomb]: Rarity.VeryRare,
    [Symbol.Milk]: Rarity.Common,
    [Symbol.Mine]: Rarity.Rare,
    [Symbol.Miner]: Rarity.Common,
    [Symbol.Monkey]: Rarity.Common,
    [Symbol.Moon]: Rarity.Rare,
    [Symbol.Mouse]: Rarity.Common,
    [Symbol.MrsFruit]: Rarity.Rare,
    [Symbol.Ninja]: Rarity.Uncommon,
    [Symbol.Omelette]: Rarity.Rare,
    [Symbol.Orange]: Rarity.Uncommon,
    [Symbol.Ore]: Rarity.Common,
    [Symbol.Owl]: Rarity.Common,
    [Symbol.Oyster]: Rarity.Common,
    [Symbol.Peach]: Rarity.Uncommon,
    [Symbol.Pear]: Rarity.Rare,
    [Symbol.Pearl]: Rarity.Common,
    [Symbol.Pirate]: Rarity.VeryRare,
    [Symbol.Pinata]: Rarity.Uncommon,
    [Symbol.Plum]: Rarity.Uncommon,
    [Symbol.Present]: Rarity.Common,
    [Symbol.Pufferfish]: Rarity.Uncommon,
    [Symbol.Rabbit]: Rarity.Uncommon,
    [Symbol.RabbitFluff]: Rarity.Uncommon,
    [Symbol.Rain]: Rarity.Uncommon,
    [Symbol.RemovalCapsule]: Rarity.Uncommon,
    [Symbol.RerollCapsule]: Rarity.Uncommon,
    [Symbol.RobinHood]: Rarity.Rare,
    [Symbol.Ruby]: Rarity.Rare,
    [Symbol.Safe]: Rarity.Uncommon,
    [Symbol.SandDollar]: Rarity.Uncommon,
    [Symbol.Sapphire]: Rarity.Uncommon,
    [Symbol.Seed]: Rarity.Common,
    [Symbol.ShinyPebble]: Rarity.Common,
    [Symbol.SilverArrow]: Rarity.Rare,
    [Symbol.Sloth]: Rarity.Uncommon,
    [Symbol.Snail]: Rarity.Common,
    [Symbol.Spades]: Rarity.Uncommon,
    [Symbol.Spirit]: Rarity.Rare,
    [Symbol.Strawberry]: Rarity.Rare,
    [Symbol.Sun]: Rarity.Rare,
    [Symbol.Target]: Rarity.Uncommon,
    [Symbol.TediumCapsule]: Rarity.Uncommon,
    [Symbol.Thief]: Rarity.Uncommon,
    [Symbol.ThreeSidedDie]: Rarity.Common,
    [Symbol.TimeCapsule]: Rarity.Uncommon,
    [Symbol.Toddler]: Rarity.Common,
    [Symbol.Tomb]: Rarity.Rare,
    [Symbol.TreasureChest]: Rarity.Rare,
    [Symbol.Turtle]: Rarity.Common,
    [Symbol.Urn]: Rarity.Common,
    [Symbol.VoidCreature]: Rarity.Uncommon,
    [Symbol.VoidFruit]: Rarity.Uncommon,
    [Symbol.VoidStone]: Rarity.Uncommon,
    [Symbol.Watermelon]: Rarity.VeryRare,
    [Symbol.WealthyCapsule]: Rarity.Uncommon,
    [Symbol.Wildcard]: Rarity.VeryRare,
    [Symbol.Wine]: Rarity.Uncommon,
    [Symbol.Witch]: Rarity.Rare,
    [Symbol.Wolf]: Rarity.Uncommon,
    [Symbol.Unknown]: Rarity.Special,
};

export const SYMBOL_VALUES: Record<Symbol, number> = {
    [Symbol.Amethyst]: 1,
    [Symbol.Anchor]: 1,
    [Symbol.Apple]: 3,
    [Symbol.Banana]: 1,
    [Symbol.BananaPeel]: 1,
    [Symbol.BarofSoap]: 1,
    [Symbol.Bartender]: 3,
    [Symbol.Bear]: 2,
    [Symbol.Beastmaster]: 2,
    [Symbol.Bee]: 1,
    [Symbol.Beehive]: 3,
    [Symbol.Beer]: 2,
    [Symbol.BigOre]: 2,
    [Symbol.BigUrn]: 2,
    [Symbol.Billionaire]: 0,
    [Symbol.BountyHunter]: 1,
    [Symbol.BronzeArrow]: 0,
    [Symbol.Bubble]: 2,
    [Symbol.BuffingCapsule]: 0,
    [Symbol.Candy]: 1,
    [Symbol.CardShark]: 3,
    [Symbol.Cat]: 1,
    [Symbol.Cheese]: 1,
    [Symbol.Chef]: 2,
    [Symbol.ChemicalSeven]: 0,
    [Symbol.Cherry]: 1,
    [Symbol.Chick]: 1,
    [Symbol.Chicken]: 2,
    [Symbol.Clubs]: 1,
    [Symbol.Coal]: 0,
    [Symbol.Coconut]: 1,
    [Symbol.CoconutHalf]: 2,
    [Symbol.Coin]: 1,
    [Symbol.Comedian]: 3,
    [Symbol.Cow]: 3,
    [Symbol.Crab]: 1,
    [Symbol.Crow]: 2,
    [Symbol.Cultist]: 0,
    [Symbol.Dame]: 2,
    [Symbol.Diamond]: 5,
    [Symbol.Diamonds]: 1,
    [Symbol.Diver]: 2,
    [Symbol.Dog]: 1,
    [Symbol.Dove]: 2,
    [Symbol.Dud]: 0,
    [Symbol.Dwarf]: 1,
    [Symbol.Egg]: 1,
    [Symbol.EldritchCreature]: 4,
    [Symbol.Emerald]: 3,
    [Symbol.Empty]: 0,
    [Symbol.EssenceCapsule]: -12,
    [Symbol.Farmer]: 2,
    [Symbol.FiveSidedDie]: 0,
    [Symbol.Flower]: 1,
    [Symbol.FrozenFossil]: 0,
    [Symbol.Gambler]: 1,
    [Symbol.GeneralZaroff]: 1,
    [Symbol.Geologist]: 2,
    [Symbol.GoldenArrow]: 0,
    [Symbol.GoldenEgg]: 4,
    [Symbol.Goldfish]: 1,
    [Symbol.Golem]: 0,
    [Symbol.Goose]: 1,
    [Symbol.Hearts]: 1,
    [Symbol.HexOfDestruction]: 3,
    [Symbol.HexOfDraining]: 3,
    [Symbol.HexOfEmptiness]: 3,
    [Symbol.HexOfHoarding]: 3,
    [Symbol.HexOfMidas]: 3,
    [Symbol.HexOfTedium]: 3,
    [Symbol.HexOfThievery]: 3,
    [Symbol.Highlander]: 6,
    [Symbol.Honey]: 3,
    [Symbol.Hooligan]: 2,
    [Symbol.HustlingCapsule]: -7,
    [Symbol.ItemCapsule]: 0,
    [Symbol.Jellyfish]: 2,
    [Symbol.Joker]: 3,
    [Symbol.Key]: 1,
    [Symbol.KingMidas]: 1,
    [Symbol.LightBulb]: 1,
    [Symbol.Lockbox]: 1,
    [Symbol.LuckyCapsule]: 0,
    [Symbol.MagicKey]: 2,
    [Symbol.Magpie]: -1,
    [Symbol.Martini]: 3,
    [Symbol.MatryoshkaDoll1]: 0,
    [Symbol.MatryoshkaDoll2]: 1,
    [Symbol.MatryoshkaDoll3]: 2,
    [Symbol.MatryoshkaDoll4]: 3,
    [Symbol.MatryoshkaDoll5]: 4,
    [Symbol.MegaChest]: 3,
    [Symbol.MidasBomb]: 0,
    [Symbol.Milk]: 1,
    [Symbol.Mine]: 4,
    [Symbol.Miner]: 1,
    [Symbol.Monkey]: 1,
    [Symbol.Moon]: 3,
    [Symbol.Mouse]: 1,
    [Symbol.MrsFruit]: 2,
    [Symbol.Ninja]: 2,
    [Symbol.Omelette]: 3,
    [Symbol.Orange]: 2,
    [Symbol.Ore]: 1,
    [Symbol.Owl]: 1,
    [Symbol.Oyster]: 1,
    [Symbol.Peach]: 2,
    [Symbol.Pear]: 1,
    [Symbol.Pearl]: 1,
    [Symbol.Pirate]: 2,
    [Symbol.Pinata]: 1,
    [Symbol.Plum]: 2,
    [Symbol.Present]: 0,
    [Symbol.Pufferfish]: 2,
    [Symbol.Rabbit]: 1,
    [Symbol.RabbitFluff]: 2,
    [Symbol.Rain]: 2,
    [Symbol.RemovalCapsule]: 0,
    [Symbol.RerollCapsule]: 0,
    [Symbol.RobinHood]: -4,
    [Symbol.Ruby]: 3,
    [Symbol.Safe]: 1,
    [Symbol.SandDollar]: 2,
    [Symbol.Sapphire]: 2,
    [Symbol.Seed]: 1,
    [Symbol.ShinyPebble]: 1,
    [Symbol.SilverArrow]: 0,
    [Symbol.Sloth]: 0,
    [Symbol.Snail]: 0,
    [Symbol.Spades]: 1,
    [Symbol.Spirit]: 6,
    [Symbol.Strawberry]: 3,
    [Symbol.Sun]: 3,
    [Symbol.Target]: 2,
    [Symbol.TediumCapsule]: 0,
    [Symbol.Thief]: -1,
    [Symbol.ThreeSidedDie]: 0,
    [Symbol.TimeCapsule]: 0,
    [Symbol.Toddler]: 1,
    [Symbol.Tomb]: 3,
    [Symbol.TreasureChest]: 2,
    [Symbol.Turtle]: 0,
    [Symbol.Urn]: 1,
    [Symbol.VoidCreature]: 0,
    [Symbol.VoidFruit]: 0,
    [Symbol.VoidStone]: 0,
    [Symbol.Watermelon]: 4,
    [Symbol.WealthyCapsule]: 0,
    [Symbol.Wildcard]: 0,
    [Symbol.Wine]: 2,
    [Symbol.Witch]: 2,
    [Symbol.Wolf]: 2,
    [Symbol.Unknown]: -1,
};

export enum ArrowDirections {
    N = "N",
    NE = "NE",
    E = "E",
    SE = "SE",
    S = "S",
    SW = "SW",
    W = "W",
    NW = "NW",
}