import { Item } from "../common/models/item";

/*
The written description of all items in the game. The following rules should apply when rendering:
- :this: refers to the source symbol, and should be rendered as the image for such.
- :xxx: refers to the symbol, item, or group xxx. It should be rendered as such.
- :coinXX: refers to the coin followed by the number XX, rendered in gold. The same applies for essence, removal, and reroll tokens.
- Each instance of the below should be rendered in red:
    - destroy(ed/s)
    - transform
    - remove(d/s)
    - any number
    - any percent
    - Adds
*/

export const ITEM_DESCRIPTIONS: Record<Item, string> = {
    [Item.AdoptionPapers]: "You may destroy this item and choose 3 symbols to add. The possible symbols are :animal:.",
    [Item.AdoptionPapersEssence]: "Destroys itself after 7 :animal: are added. Gives :coin77: when destroyed.",
    [Item.AncientLizardBlade]: "Gives :coin9: each spin. Gives :coin1: less for each symbol in your inventory with a quantity of 2 or more. Canot give less than :coin0:.",
    [Item.AncientLizardBladeEssence]: "Gives :coin40: and is destroyed when you spin. Gives :coin8: less for each symbol in your inventory with a quantity of 2 or more. Cannot give less than :coin0:. This effect ignores :empty:.",
    [Item.AnthropologyDegree]: ":human: give :coin1: more.",
    [Item.AnthropologyDegreeEssence]: "Destroys itself if there are at least 9 :human:. When destroyed, :human: give 1.5x more this game.",
    [Item.InstantRamen]: "You add an additional item after each rent payment.",
    [Item.InstantRamenEssence]: "Destroys itself when you skip an item. When destroyed, you add 2 items.",
    [Item.BarrelODwarves]: "You may destroy this item and add 7 :dwarf:.",
    [Item.BarrelODwarvesEssence]: "Destroys itself after 7 :dwarf: are removed. Removes all :dwarf: before each spin. Gives :coin17: whenever :dwarf: are removed.",
    [Item.Birdhouse]: ":bird: give :coin1: more.",
    [Item.BirdhouseEssence]: "Destroys itself if 3 or more :bird: are adjacent. When destroyed, :bird: give :coin2: more this game.",
    [Item.BlackCat]: "Gives :coin9: whenever you gain a multiple of :coin13: afte4r a spin. :cat: give 2x more :coin:.",
    [Item.BlackCatEssence]: "Destroys itself if there are at least 13 :cat:. When destroyed, :cat: give 13x more this game.",
    [Item.BlackPepper]: "Gives :coin1: whenever a symbol is destroyed.",
    [Item.BlackPepperEssence]: "Gives :coin10: whenever a symbol is destroyed. Destroys itself afterward.",
    [Item.BluePepper]: "Gives :coin3: if there are at least 3 :empty:.",
    [Item.BluePepperEssence]: "Gives :coin30: if there are at least 3 :empty:. Destroys itself afterwards.",
    [Item.BlueSuits]: "You may destroy this after 7 spins. Adds a :clubs: and :spades: when destroyed.",
    [Item.BlueSuitsEssence]: "Destroys itself if there are at least 4 :clubs: and :spades:. When destroyed, :clubs: and :spades: give :coin1: more this game.",
    [Item.BoosterPack]: "You may destroy this item and choose 4 Common symbols, 3 Uncommon symbols, and 1 Rare symbol to add.",
    [Item.BoosterPackEssence]: "Destroys itself after 12 spins. When destroyed, you choose 2 Uncommon and 1 Very Rare symbol to add.",
    [Item.BowlingBall]: "Gives :coin3:.",
    [Item.BowlingBallEssence]: "",
    [Item.BrownPepper]: "Gives :coin1: whenever a symbol is added.",
    [Item.BrownPepperEssence]: "",
    [Item.CapsuleMachine]: "The effects of :capsule: happen 2 times.",
    [Item.CapsuleMachineEssence]: "",
    [Item.CardboardBox]: "Gives :removal1: every 10 spins.",
    [Item.CardboardBoxEssence]: "",
    [Item.CheckeredFlag]: ":slow: take 1 less spin to give :coin:",
    [Item.CheckeredFlagEssence]: "",
    [Item.ChickenCoop]: ":chickenstuff: give :coin2: more. :chicken: are 3x more likely to add symbols. :egg: are 3x more likely to transform.",
    [Item.ChickenCoopEssence]: "",
    [Item.ChiliPowder]: "Gives :coin2: for each :pepper:.",
    [Item.ChiliPowderEssence]: "",
    [Item.CleaningRag]: ":gem: give :coin1: more.",
    [Item.CleaningRagEssence]: "",
    [Item.ClearSky]: ":sun: and :moon: affect non-adjacent symbols as well.",
    [Item.ClearSkyEssence]: "",
    [Item.Coffee]: "If you can't afford your rent, you may destroy this item and spin an additional time.",
    [Item.CoffeeEssence]: "",
    [Item.CoinOnAString]: "Gives :coin1:. Removes all :coin: before each spin. Gives :coin3: whenever :coin: is removed.",
    [Item.CoinOnAStringEssence]: "",
    [Item.ComfyPillow]: "If you have 1 spin left before your rent is due, you may skip your next spin. If you do, at least 1 of the items to add after paying rent will be Rare or better.",
    [Item.ComfyPillowEssence]: "",
    [Item.CompostHeap]: ":seed: is added whenever 3 symbols are destroyed. :seed: will only grow into Uncommon or better symbols.",
    [Item.CompostHeapEssence]: "",
    [Item.ConveyorBelt]: ":spawner0: are 2x more likely to add symbols.",
    [Item.ConveyorBeltEssence]: "",
    [Item.Copycat]: ":cat: are :wildcard:.",
    [Item.CopycatEssence]: "",
    [Item.CreditCard]: "Every 7 spins, you have 17 more symbols to choose from after a spin.",
    [Item.CreditCardEssence]: "",
    [Item.CursedKatana]: ":ninja: give :coin2: more for each other :ninja:.",
    [Item.CursedKatanaEssence]: "",
    [Item.CyanPepper]: "Gives :coin3: unless 3 or more symbols are the same. This effect ignores :empty:.",
    [Item.CyanPepperEssence]: "",
    [Item.DarkHumor]: ":darkhumor: give 3x more :coin: when adjacent to :comedian:. :comedian: are Uncommon instead of Rare.",
    [Item.DarkHumorEssence]: "",
    [Item.DevilsDeal]: "You may destroy this item and add 6 :dud: instead of paying rent.",
    [Item.DevilsDealEssence]: "",
    [Item.Dishwasher]: "Gives :essence1: every 12 spins.",
    [Item.DishwasherEssence]: "",
    [Item.DwarvenAnvil]: ":dwarf: give 2x more :coin: and destroy adjacent :ore: and :big_ore:.",
    [Item.DwarvenAnvilEssence]: "",
    [Item.EggCarton]: "Puts all :egg: in this item before each spin. Gives :coin1: for each :egg: in this item, up to a maximum of :coin6: each spin.",
    [Item.EggCartonEssence]: "",
    [Item.Fertilizer]: ":seed: will only grow into Rare or better symbols. :seed: are 50% more likely to grow.",
    [Item.FertilizerEssence]: "",
    [Item.FifthAce]: ":clubs: and :spades: give :coin1: more when adjacent to :diamonds: and :hearts:. :diamonds: and :hearts: give :coin1: more when adjacent to :clubs: and :spades:.",
    [Item.FifthAceEssence]: "",
    [Item.FishBowl]: "Puts all :goldfish: in this item before each spin. Gives :coin1: for each :goldfish: in this item.",
    [Item.FishBowlEssence]: "",
    [Item.Flush]: ":suit: are Common instead of Uncommon. Removes all :suit: before each spin. Gives :coin12: whenever :suit: are removed.",
    [Item.FlushEssence]: "",
    [Item.FourLeafClover]: "Gives :coin4:.",
    [Item.FourLeafCloverEssence]: "",
    [Item.FrozenPizza]: "You add an extra symbol after every 2 spins.",
    [Item.FrozenPizzaEssence]: "",
    [Item.FruitBasket]: ":fruit: give :coin1: more.",
    [Item.FruitBasketEssence]: "",
    [Item.FryingPan]: ":egg: are destroyed when adjacent to :omelettestuff:. Adds :omelette: whenever :egg: are destroyed.",
    [Item.FryingPanEssence]: "",
    [Item.GoldenCarrot]: "You are 5x more likely to find Uncommon, Rare, and Very Rare symbols. :rabbit: give 5x more :coin:.",
    [Item.GoldenCarrotEssence]: "",
    [Item.Goldilocks]: "You may destroy this item and add 3 :bear:.",
    [Item.GoldilocksEssence]: "",
    [Item.GraveRobber]: ":spiritbox: have a 66% chance of being destroyed.",
    [Item.GraveRobberEssence]: "",
    [Item.GrayPepper]: "Gives :coin6: whenever you spend :removal:.",
    [Item.GrayPepperEssence]: "",
    [Item.GreenPepper]: "Gives :coin3: if at least 3 symbols are the same and not :empty:.",
    [Item.GreenPepperEssence]: "",
    [Item.Guillotine]: ":billionaire: are destroyed.",
    [Item.GuillotineEssence]: "",
    [Item.HappyHour]: ":booze: give :coin1: more.",
    [Item.HappyHourEssence]: "",
    [Item.HolyWater]: ":hex: have no effect and give :coin1: more.",
    [Item.HolyWaterEssence]: "",
    [Item.Horseshoe]: "Gives :coin2:.",
    [Item.HorseshoeEssence]: "",
    [Item.ItemMissing]: "",
    [Item.Jackolantern]: ":halloween: give 2x more :coin:.",
    [Item.JackolanternEssence]: "",
    [Item.KyleTheKernite]: ":kyle: give :coin1: more.",
    [Item.KyleTheKerniteEssence]: "",
    [Item.LeftyTheRabbit]: "Adds :rabbit_fluff: every 10 spins. :rabbit: and :rabbit_fluff: in the leftmost column give 2x more :coin:.",
    [Item.LeftyTheRabbitEssence]: "",
    [Item.Lemon]: ":empty: give :coin1:.",
    [Item.LemonEssence]: "",
    [Item.LimePepper]: "Gives :coin6: when you spend :reroll1:.",
    [Item.LimePepperEssence]: "",
    [Item.LintRoller]: "Removes all :rabbit_fluff: before each spin. Gives :coin12: whenever :rabbit_fluff: are removed.",
    [Item.LintRollerEssence]: "",
    [Item.Lockpick]: ":chest: have a 35% chance of being destroyed.",
    [Item.LockpickEssence]: "",
    [Item.LootingGlove]: ":box: give 1.5x more :coin: when destroyed.",
    [Item.LootingGloveEssence]: "",
    [Item.LuckyCarrot]: "You are 3x more likely to find Uncommon, Rare, and Very Rare symbols. :rabbit: give 3x more :coin:.",
    [Item.LuckyCarrotEssence]: "",
    [Item.LuckyCat]: "You are 1.3x more likely to find Uncommon, Rare, and Very Rare symbols for each :cat:.",
    [Item.LuckyCatEssence]: "",
    [Item.LuckyDice]: ":d3: will always roll :d3:. :d5: will always roll :d5:.",
    [Item.LuckyDiceEssence]: "",
    [Item.LuckySeven]: "If you have 3 of this item, they are destroyed and give :coin77: total.",
    [Item.LuckySevenEssence]: "",
    [Item.Lunchbox]: "You may destroy this item and choose 3 symbols to add. The possible symbols are :food:.",
    [Item.LunchboxEssence]: "",
    [Item.MaxwellTheBear]: ":bear: give 1.5x more :coin:.",
    [Item.MaxwellTheBearEssence]: "",
    [Item.MiningPick]: "Gives :coin10: whenever :ore: or :big_ore: are destroyed.",
    [Item.MiningPickEssence]: "",
    [Item.MobiusStrip]: ":box: have a 50% chance of being added when destroyed. This effect can only happen 7 times per spin.",
    [Item.MobiusStripEssence]: "",
    [Item.NinjaAndMouse]: ":ninja: and :mouse: give 6x more Coin when adjacent to each other. This effect only applies once per spin.",
    [Item.NinjaAndMouseEssence]: "",
    [Item.NoriTheRabbit]: ":rabbit: and :rabbit_fluff: give :coin1: more.",
    [Item.NoriTheRabbitEssence]: "",
    [Item.OilCan]: "You may re-spin a column of symbols once every 5 spins. Symbols in the re-spun column give 2x more :coin:.",
    [Item.OilCanEssence]: "",
    [Item.OswaldTheMonkey]: ":monkey: give 2x more :coin:.",
    [Item.OswaldTheMonkeyEssence]: "",
    [Item.PiggyBank]: "You put :coin2: in this item each spin. You may destroy this item and gain 2.5x the :coin: inside it.",
    [Item.PiggyBankEssence]: "",
    [Item.PinkPepper]: "Gives :coin2: whenever you skip.",
    [Item.PinkPepperEssence]: "",
    [Item.PizzaTheCat]: ":cat: give :coin1: more.",
    [Item.PizzaTheCatEssence]: "",
    [Item.PoolBall]: "Gives :coin1:.",
    [Item.PoolBallEssence]: "",
    [Item.Popsicle]: "The conditional effects of essences must happen 2 times for them to be destroyed.",
    [Item.PopsicleEssence]: "",
    [Item.Protractor]: "Every 3 spins, symbols in a corner are considered adjacent to all symbols.",
    [Item.ProtractorEssence]: "",
    [Item.PurplePepper]: "Gives :coin: if 3 or more of the same symbol are adjacent and not :empty:.",
    [Item.PurplePepperEssence]: "",
    [Item.QuigleyTheWolf]: ":wolf: give :coin1: more. :dog: transform into :wolf:.",
    [Item.QuigleyTheWolfEssence]: "",
    [Item.Quiver]: ":arrow: point 2 directions.",
    [Item.QuiverEssence]: "",
    [Item.RainCloud]: ":raindrop: give :coin1: more and are Common instead of Uncommon.",
    [Item.RainCloudEssence]: "",
    [Item.Recycling]: "Gives :reroll1: each spin.",
    [Item.RecyclingEssence]: "",
    [Item.RedPepper]: "Gives :coin5: if every symbol is different",
    [Item.RedPepperEssence]: "",
    [Item.RedSuits]: "You may destroy this after 7 spins. Adds a :diamonds: and :hearts: when destroyed.",
    [Item.RedSuitsEssence]: "",
    [Item.Reroll]: ":d3: that roll less than a :d3_2: and :d5: that roll less than a :d5_3: will reroll once.",
    [Item.RerollEssence]: "",
    [Item.RickyTheBanana]: ":banana: and :banana_peel: give :coin2: more.",
    [Item.RickyTheBananaEssence]: "",
    [Item.RitualCandle]: ":fossillikes: give :coin1: more.",
    [Item.RitualCandleEssence]: "",
    [Item.RustyGear]: "If 3 or more of the same symbol are adjacent and not :empty:, they give 2x more :coin:.",
    [Item.RustyGearEssence]: "",
    [Item.ShatteredMirror]: "Gives :coin24: every 7 spins. You have 1 less symbol to choose from after a spin.",
    [Item.ShatteredMirrorEssence]: "",
    [Item.SheddingSeason]: ":rabbit: have a 15% chance of adding :rabbit_fluff:.",
    [Item.SheddingSeasonEssence]: "",
    [Item.Shrine]: ":organism: add :spirit: when destroyed.",
    [Item.ShrineEssence]: "",
    [Item.Sunglasses]: "Gives :removal1: each spin if you have :removal3: or more.",
    [Item.SunglassesEssence]: "",
    [Item.SwappingDevice]: "You may swap the positions of 2 symbols once per spin.",
    [Item.SwappingDeviceEssence]: "",
    [Item.SwearJar]: "You put :coin: in this item each time you spin and gain :coin35: or less. You may destroy this item and gain 3x the :coin: inside it.",
    [Item.SwearJarEssence]: "",
    [Item.SymbolBombBig]: "You may destroy this item and choose 4 symbols to add.",
    [Item.SymbolBombBigEssence]: "",
    [Item.SymbolBombQuantum]: "You may destroy this item and choose 9 symbols to add that were previously seen after a spin but weren't added.",
    [Item.SymbolBombQuantumEssence]: "",
    [Item.SymbolBombSmall]: "You may destroy this item and choose 2 symbols to add.",
    [Item.SymbolBombSmallEssence]: "",
    [Item.SymbolBombVeryBig]: "You may destroy this item and choose 8 symbols to add.",
    [Item.SymbolBombVeryBigEssence]: "",
    [Item.TaxEvasion]: "If a symbol would take :coin:, it takes :coin1: less.",
    [Item.TaxEvasionEssence]: "",
    [Item.Telescope]: "Every 3 spins, all symbols are considered adjacent.",
    [Item.TelescopeEssence]: "",
    [Item.TimeMachine]: ":coal: take 5 less spins to transform. :destroyable_matryoshka: take 2 less spins to be destroyed. :time_machine3: take 5 less spins to be destroyed.",
    [Item.TimeMachineEssence]: "",
    [Item.TreasureMap]: "You may destroy this item after 20 spins. Adds :key: and :treasure_chest: when destroyed.",
    [Item.TreasureMapEssence]: "",
    [Item.TripleCoins]: ":coin: give 3x more :coin:.",
    [Item.TripleCoinsEssence]: "",
    [Item.TurtleAndRabbit]: "Gives :coin77: and is destroyed if :rabbit: is in the leftmost column and :turtle: is in the rightmost column.",
    [Item.TurtleAndRabbitEssence]: "",
    [Item.Undertaker]: ":spirit: cannot be destroyed.",
    [Item.UndertakerEssence]: "",
    [Item.VoidParty]: ":void: are Common instead of Uncommon. :void: have a 50% chance of being added when destroyed. This effect can only happen 7 times each spin.",
    [Item.VoidPartyEssence]: "",
    [Item.VoidPortal]: "Gives :coin1: for every 8 symbols destroyed this game.",
    [Item.VoidPortalEssence]: "",
    [Item.WantedPoster]: ":thief: give 3.5x more :coin:.",
    [Item.WantedPosterEssence]: "",
    [Item.WateringCan]: ":seed: are 100% more likely to grow. :seed: give :coin12: more.",
    [Item.WateringCanEssence]: "",
    [Item.WhitePepper]: "Gives :coin3: whenever you gain a multiple of :coin3: after a spin.",
    [Item.WhitePepperEssence]: "",
    [Item.XRayMachine]: ":ore: and :big_ore: will only add Rare or better symbols.",
    [Item.XRayMachineEssence]: "",
    [Item.YellowPepper]: "Gives :coin2: if none of the symbols are :empty:.",
    [Item.YellowPepperEssence]: "",
    [Item.ZaroffsContract]: ":bounty_hunter: destroy adjacent :human:. :bounty_hunter: give :coin25: for each symbol destroyed.",
    [Item.ZaroffsContractEssence]: "",
};