// Generated by scrape_items.py
import { Item } from "../common/models/item"


const adoption_papers = require("../img/items/adoption_papers.png");
const adoption_papers_essence = require("../img/items/adoption_papers_essence.png");
const ancient_lizard_blade = require("../img/items/ancient_lizard_blade.png");
const ancient_lizard_blade_essence = require("../img/items/ancient_lizard_blade_essence.png");
const anthropology_degree = require("../img/items/anthropology_degree.png");
const anthropology_degree_essence = require("../img/items/anthropology_degree_essence.png");
const bag_of_holding = require("../img/items/bag_of_holding.png");
const bag_of_holding_essence = require("../img/items/bag_of_holding_essence.png");
const barrel_o_dwarves = require("../img/items/barrel_o_dwarves.png");
const barrel_o_dwarves_essence = require("../img/items/barrel_o_dwarves_essence.png");
const birdhouse = require("../img/items/birdhouse.png");
const birdhouse_essence = require("../img/items/birdhouse_essence.png");
const black_cat = require("../img/items/black_cat.png");
const black_cat_essence = require("../img/items/black_cat_essence.png");
const black_pepper = require("../img/items/black_pepper.png");
const black_pepper_essence = require("../img/items/black_pepper_essence.png");
const blue_pepper = require("../img/items/blue_pepper.png");
const blue_pepper_essence = require("../img/items/blue_pepper_essence.png");
const blue_suits = require("../img/items/blue_suits.png");
const blue_suits_essence = require("../img/items/blue_suits_essence.png");
const booster_pack = require("../img/items/booster_pack.png");
const booster_pack_essence = require("../img/items/booster_pack_essence.png");
const bowling_ball = require("../img/items/bowling_ball.png");
const bowling_ball_essence = require("../img/items/bowling_ball_essence.png");
const brown_pepper = require("../img/items/brown_pepper.png");
const brown_pepper_essence = require("../img/items/brown_pepper_essence.png");
const capsule_machine = require("../img/items/capsule_machine.png");
const capsule_machine_essence = require("../img/items/capsule_machine_essence.png");
const cardboard_box = require("../img/items/cardboard_box.png");
const cardboard_box_essence = require("../img/items/cardboard_box_essence.png");
const checkered_flag = require("../img/items/checkered_flag.png");
const checkered_flag_essence = require("../img/items/checkered_flag_essence.png");
const chicken_coop = require("../img/items/chicken_coop.png");
const chicken_coop_essence = require("../img/items/chicken_coop_essence.png");
const chili_powder = require("../img/items/chili_powder.png");
const chili_powder_essence = require("../img/items/chili_powder_essence.png");
const cleaning_rag = require("../img/items/cleaning_rag.png");
const cleaning_rag_essence = require("../img/items/cleaning_rag_essence.png");
const clear_sky = require("../img/items/clear_sky.png");
const clear_sky_essence = require("../img/items/clear_sky_essence.png");
const coffee = require("../img/items/coffee.png");
const coffee_essence = require("../img/items/coffee_essence.png");
const coin_on_a_string = require("../img/items/coin_on_a_string.png");
const coin_on_a_string_essence = require("../img/items/coin_on_a_string_essence.png");
const comfy_pillow = require("../img/items/comfy_pillow.png");
const comfy_pillow_essence = require("../img/items/comfy_pillow_essence.png");
const compost_heap = require("../img/items/compost_heap.png");
const compost_heap_essence = require("../img/items/compost_heap_essence.png");
const conveyor_belt = require("../img/items/conveyor_belt.png");
const conveyor_belt_essence = require("../img/items/conveyor_belt_essence.png");
const copycat = require("../img/items/copycat.png");
const copycat_essence = require("../img/items/copycat_essence.png");
const credit_card = require("../img/items/credit_card.png");
const credit_card_essence = require("../img/items/credit_card_essence.png");
const cursed_katana = require("../img/items/cursed_katana.png");
const cursed_katana_essence = require("../img/items/cursed_katana_essence.png");
const cyan_pepper = require("../img/items/cyan_pepper.png");
const cyan_pepper_essence = require("../img/items/cyan_pepper_essence.png");
const dark_humor = require("../img/items/dark_humor.png");
const dark_humor_essence = require("../img/items/dark_humor_essence.png");
const devils_deal = require("../img/items/devils_deal.png");
const devils_deal_essence = require("../img/items/devils_deal_essence.png");
const dishwasher = require("../img/items/dishwasher.png");
const dishwasher_essence = require("../img/items/dishwasher_essence.png");
const dwarven_anvil = require("../img/items/dwarven_anvil.png");
const dwarven_anvil_essence = require("../img/items/dwarven_anvil_essence.png");
const egg_carton = require("../img/items/egg_carton.png");
const egg_carton_essence = require("../img/items/egg_carton_essence.png");
const fertilizer = require("../img/items/fertilizer.png");
const fertilizer_essence = require("../img/items/fertilizer_essence.png");
const fifth_ace = require("../img/items/fifth_ace.png");
const fifth_ace_essence = require("../img/items/fifth_ace_essence.png");
const fish_bowl = require("../img/items/fish_bowl.png");
const fish_bowl_essence = require("../img/items/fish_bowl_essence.png");
const flush = require("../img/items/flush.png");
const flush_essence = require("../img/items/flush_essence.png");
const four_leaf_clover = require("../img/items/four_leaf_clover.png");
const four_leaf_clover_essence = require("../img/items/four_leaf_clover_essence.png");
const frozen_pizza = require("../img/items/frozen_pizza.png");
const frozen_pizza_essence = require("../img/items/frozen_pizza_essence.png");
const fruit_basket = require("../img/items/fruit_basket.png");
const fruit_basket_essence = require("../img/items/fruit_basket_essence.png");
const frying_pan = require("../img/items/frying_pan.png");
const frying_pan_essence = require("../img/items/frying_pan_essence.png");
const golden_carrot = require("../img/items/golden_carrot.png");
const golden_carrot_essence = require("../img/items/golden_carrot_essence.png");
const goldilocks = require("../img/items/goldilocks.png");
const goldilocks_essence = require("../img/items/goldilocks_essence.png");
const grave_robber = require("../img/items/grave_robber.png");
const grave_robber_essence = require("../img/items/grave_robber_essence.png");
const gray_pepper = require("../img/items/gray_pepper.png");
const gray_pepper_essence = require("../img/items/gray_pepper_essence.png");
const green_pepper = require("../img/items/green_pepper.png");
const green_pepper_essence = require("../img/items/green_pepper_essence.png");
const guillotine = require("../img/items/guillotine.png");
const guillotine_essence = require("../img/items/guillotine_essence.png");
const happy_hour = require("../img/items/happy_hour.png");
const happy_hour_essence = require("../img/items/happy_hour_essence.png");
const holy_water = require("../img/items/holy_water.png");
const holy_water_essence = require("../img/items/holy_water_essence.png");
const horseshoe = require("../img/items/horseshoe.png");
const horseshoe_essence = require("../img/items/horseshoe_essence.png");
const item_missing = require("../img/items/item_missing.png");
const jackolantern = require("../img/items/jackolantern.png");
const jackolantern_essence = require("../img/items/jackolantern_essence.png");
const kyle_the_kernite = require("../img/items/kyle_the_kernite.png");
const kyle_the_kernite_essence = require("../img/items/kyle_the_kernite_essence.png");
const lefty_the_rabbit = require("../img/items/lefty_the_rabbit.png");
const lefty_the_rabbit_essence = require("../img/items/lefty_the_rabbit_essence.png");
const lemon = require("../img/items/lemon.png");
const lemon_essence = require("../img/items/lemon_essence.png");
const lime_pepper = require("../img/items/lime_pepper.png");
const lime_pepper_essence = require("../img/items/lime_pepper_essence.png");
const lint_roller = require("../img/items/lint_roller.png");
const lint_roller_essence = require("../img/items/lint_roller_essence.png");
const lockpick = require("../img/items/lockpick.png");
const lockpick_essence = require("../img/items/lockpick_essence.png");
const looting_glove = require("../img/items/looting_glove.png");
const looting_glove_essence = require("../img/items/looting_glove_essence.png");
const lucky_carrot = require("../img/items/lucky_carrot.png");
const lucky_carrot_essence = require("../img/items/lucky_carrot_essence.png");
const lucky_cat = require("../img/items/lucky_cat.png");
const lucky_cat_essence = require("../img/items/lucky_cat_essence.png");
const lucky_dice = require("../img/items/lucky_dice.png");
const lucky_dice_essence = require("../img/items/lucky_dice_essence.png");
const lucky_seven = require("../img/items/lucky_seven.png");
const lucky_seven_essence = require("../img/items/lucky_seven_essence.png");
const lunchbox = require("../img/items/lunchbox.png");
const lunchbox_essence = require("../img/items/lunchbox_essence.png");
const maxwell_the_bear = require("../img/items/maxwell_the_bear.png");
const maxwell_the_bear_essence = require("../img/items/maxwell_the_bear_essence.png");
const mining_pick = require("../img/items/mining_pick.png");
const mining_pick_essence = require("../img/items/mining_pick_essence.png");
const mobius_strip = require("../img/items/mobius_strip.png");
const mobius_strip_essence = require("../img/items/mobius_strip_essence.png");
const ninja_and_mouse = require("../img/items/ninja_and_mouse.png");
const ninja_and_mouse_essence = require("../img/items/ninja_and_mouse_essence.png");
const nori_the_rabbit = require("../img/items/nori_the_rabbit.png");
const nori_the_rabbit_essence = require("../img/items/nori_the_rabbit_essence.png");
const oil_can = require("../img/items/oil_can.png");
const oil_can_essence = require("../img/items/oil_can_essence.png");
const oswald_the_monkey = require("../img/items/oswald_the_monkey.png");
const oswald_the_monkey_essence = require("../img/items/oswald_the_monkey_essence.png");
const piggy_bank = require("../img/items/piggy_bank.png");
const piggy_bank_essence = require("../img/items/piggy_bank_essence.png");
const pink_pepper = require("../img/items/pink_pepper.png");
const pink_pepper_essence = require("../img/items/pink_pepper_essence.png");
const pizza_the_cat = require("../img/items/pizza_the_cat.png");
const pizza_the_cat_essence = require("../img/items/pizza_the_cat_essence.png");
const pool_ball = require("../img/items/pool_ball.png");
const pool_ball_essence = require("../img/items/pool_ball_essence.png");
const popsicle = require("../img/items/popsicle.png");
const popsicle_essence = require("../img/items/popsicle_essence.png");
const protractor = require("../img/items/protractor.png");
const protractor_essence = require("../img/items/protractor_essence.png");
const purple_pepper = require("../img/items/purple_pepper.png");
const purple_pepper_essence = require("../img/items/purple_pepper_essence.png");
const quigley_the_wolf = require("../img/items/quigley_the_wolf.png");
const quigley_the_wolf_essence = require("../img/items/quigley_the_wolf_essence.png");
const quiver = require("../img/items/quiver.png");
const quiver_essence = require("../img/items/quiver_essence.png");
const rain_cloud = require("../img/items/rain_cloud.png");
const rain_cloud_essence = require("../img/items/rain_cloud_essence.png");
const recycling = require("../img/items/recycling.png");
const recycling_essence = require("../img/items/recycling_essence.png");
const red_pepper = require("../img/items/red_pepper.png");
const red_pepper_essence = require("../img/items/red_pepper_essence.png");
const red_suits = require("../img/items/red_suits.png");
const red_suits_essence = require("../img/items/red_suits_essence.png");
const reroll = require("../img/items/reroll.png");
const reroll_essence = require("../img/items/reroll_essence.png");
const ricky_the_banana = require("../img/items/ricky_the_banana.png");
const ricky_the_banana_essence = require("../img/items/ricky_the_banana_essence.png");
const ritual_candle = require("../img/items/ritual_candle.png");
const ritual_candle_essence = require("../img/items/ritual_candle_essence.png");
const rusty_gear = require("../img/items/rusty_gear.png");
const rusty_gear_essence = require("../img/items/rusty_gear_essence.png");
const shattered_mirror = require("../img/items/shattered_mirror.png");
const shattered_mirror_essence = require("../img/items/shattered_mirror_essence.png");
const shedding_season = require("../img/items/shedding_season.png");
const shedding_season_essence = require("../img/items/shedding_season_essence.png");
const shrine = require("../img/items/shrine.png");
const shrine_essence = require("../img/items/shrine_essence.png");
const sunglasses = require("../img/items/sunglasses.png");
const sunglasses_essence = require("../img/items/sunglasses_essence.png");
const swapping_device = require("../img/items/swapping_device.png");
const swapping_device_essence = require("../img/items/swapping_device_essence.png");
const swear_jar = require("../img/items/swear_jar.png");
const swear_jar_essence = require("../img/items/swear_jar_essence.png");
const symbol_bomb_big = require("../img/items/symbol_bomb_big.png");
const symbol_bomb_big_essence = require("../img/items/symbol_bomb_big_essence.png");
const symbol_bomb_quantum = require("../img/items/symbol_bomb_quantum.png");
const symbol_bomb_quantum_essence = require("../img/items/symbol_bomb_quantum_essence.png");
const symbol_bomb_small = require("../img/items/symbol_bomb_small.png");
const symbol_bomb_small_essence = require("../img/items/symbol_bomb_small_essence.png");
const symbol_bomb_very_big = require("../img/items/symbol_bomb_very_big.png");
const symbol_bomb_very_big_essence = require("../img/items/symbol_bomb_very_big_essence.png");
const tax_evasion = require("../img/items/tax_evasion.png");
const tax_evasion_essence = require("../img/items/tax_evasion_essence.png");
const telescope = require("../img/items/telescope.png");
const telescope_essence = require("../img/items/telescope_essence.png");
const time_machine = require("../img/items/time_machine.png");
const time_machine_essence = require("../img/items/time_machine_essence.png");
const treasure_map = require("../img/items/treasure_map.png");
const treasure_map_essence = require("../img/items/treasure_map_essence.png");
const triple_coins = require("../img/items/triple_coins.png");
const triple_coins_essence = require("../img/items/triple_coins_essence.png");
const turtle_and_rabbit = require("../img/items/turtle_and_rabbit.png");
const turtle_and_rabbit_essence = require("../img/items/turtle_and_rabbit_essence.png");
const undertaker = require("../img/items/undertaker.png");
const undertaker_essence = require("../img/items/undertaker_essence.png");
const void_party = require("../img/items/void_party.png");
const void_party_essence = require("../img/items/void_party_essence.png");
const void_portal = require("../img/items/void_portal.png");
const void_portal_essence = require("../img/items/void_portal_essence.png");
const wanted_poster = require("../img/items/wanted_poster.png");
const wanted_poster_essence = require("../img/items/wanted_poster_essence.png");
const watering_can = require("../img/items/watering_can.png");
const watering_can_essence = require("../img/items/watering_can_essence.png");
const white_pepper = require("../img/items/white_pepper.png");
const white_pepper_essence = require("../img/items/white_pepper_essence.png");
const x_ray_machine = require("../img/items/x_ray_machine.png");
const x_ray_machine_essence = require("../img/items/x_ray_machine_essence.png");
const yellow_pepper = require("../img/items/yellow_pepper.png");
const yellow_pepper_essence = require("../img/items/yellow_pepper_essence.png");
const zaroffs_contract = require("../img/items/zaroffs_contract.png");
const zaroffs_contract_essence = require("../img/items/zaroffs_contract_essence.png");

export const ItemDisabledIMG = require("../img/item_disabled.png");



export const IIDToItem = (iid: string): Item => {
    return IID_TO_ITEM.get(iid) ?? Item.ItemMissing;
}

// Internal ID to item mapping
export const IID_TO_ITEM: Map<string, Item> = new Map([
    ["adoption_papers", Item.AdoptionPapers],
    ["adoption_papers_essence", Item.AdoptionPapersEssence],
    ["ancient_lizard_blade", Item.AncientLizardBlade],
    ["ancient_lizard_blade_essence", Item.AncientLizardBladeEssence],
    ["anthropology_degree", Item.AnthropologyDegree],
    ["anthropology_degree_essence", Item.AnthropologyDegreeEssence],
    ["bag_of_holding", Item.InstantRamen],
    ["bag_of_holding_essence", Item.InstantRamenEssence],
    ["barrel_o_dwarves", Item.BarrelODwarves],
    ["barrel_o_dwarves_essence", Item.BarrelODwarvesEssence],
    ["birdhouse", Item.Birdhouse],
    ["birdhouse_essence", Item.BirdhouseEssence],
    ["black_cat", Item.BlackCat],
    ["black_cat_essence", Item.BlackCatEssence],
    ["black_pepper", Item.BlackPepper],
    ["black_pepper_essence", Item.BlackPepperEssence],
    ["blue_pepper", Item.BluePepper],
    ["blue_pepper_essence", Item.BluePepperEssence],
    ["blue_suits", Item.BlueSuits],
    ["blue_suits_essence", Item.BlueSuitsEssence],
    ["booster_pack", Item.BoosterPack],
    ["booster_pack_essence", Item.BoosterPackEssence],
    ["bowling_ball", Item.BowlingBall],
    ["bowling_ball_essence", Item.BowlingBallEssence],
    ["brown_pepper", Item.BrownPepper],
    ["brown_pepper_essence", Item.BrownPepperEssence],
    ["capsule_machine", Item.CapsuleMachine],
    ["capsule_machine_essence", Item.CapsuleMachineEssence],
    ["cardboard_box", Item.CardboardBox],
    ["cardboard_box_essence", Item.CardboardBoxEssence],
    ["checkered_flag", Item.CheckeredFlag],
    ["checkered_flag_essence", Item.CheckeredFlagEssence],
    ["chicken_coop", Item.ChickenCoop],
    ["chicken_coop_essence", Item.ChickenCoopEssence],
    ["chili_powder", Item.ChiliPowder],
    ["chili_powder_essence", Item.ChiliPowderEssence],
    ["cleaning_rag", Item.CleaningRag],
    ["cleaning_rag_essence", Item.CleaningRagEssence],
    ["clear_sky", Item.ClearSky],
    ["clear_sky_essence", Item.ClearSkyEssence],
    ["coffee", Item.Coffee],
    ["coffee_essence", Item.CoffeeEssence],
    ["coin_on_a_string", Item.CoinOnAString],
    ["coin_on_a_string_essence", Item.CoinOnAStringEssence],
    ["comfy_pillow", Item.ComfyPillow],
    ["comfy_pillow_essence", Item.ComfyPillowEssence],
    ["compost_heap", Item.CompostHeap],
    ["compost_heap_essence", Item.CompostHeapEssence],
    ["conveyor_belt", Item.ConveyorBelt],
    ["conveyor_belt_essence", Item.ConveyorBeltEssence],
    ["copycat", Item.Copycat],
    ["copycat_essence", Item.CopycatEssence],
    ["credit_card", Item.CreditCard],
    ["credit_card_essence", Item.CreditCardEssence],
    ["cursed_katana", Item.CursedKatana],
    ["cursed_katana_essence", Item.CursedKatanaEssence],
    ["cyan_pepper", Item.CyanPepper],
    ["cyan_pepper_essence", Item.CyanPepperEssence],
    ["dark_humor", Item.DarkHumor],
    ["dark_humor_essence", Item.DarkHumorEssence],
    ["devils_deal", Item.DevilsDeal],
    ["devils_deal_essence", Item.DevilsDealEssence],
    ["dishwasher", Item.Dishwasher],
    ["dishwasher_essence", Item.DishwasherEssence],
    ["dwarven_anvil", Item.DwarvenAnvil],
    ["dwarven_anvil_essence", Item.DwarvenAnvilEssence],
    ["egg_carton", Item.EggCarton],
    ["egg_carton_essence", Item.EggCartonEssence],
    ["fertilizer", Item.Fertilizer],
    ["fertilizer_essence", Item.FertilizerEssence],
    ["fifth_ace", Item.FifthAce],
    ["fifth_ace_essence", Item.FifthAceEssence],
    ["fish_bowl", Item.FishBowl],
    ["fish_bowl_essence", Item.FishBowlEssence],
    ["flush", Item.Flush],
    ["flush_essence", Item.FlushEssence],
    ["four_leaf_clover", Item.FourLeafClover],
    ["four_leaf_clover_essence", Item.FourLeafCloverEssence],
    ["frozen_pizza", Item.FrozenPizza],
    ["frozen_pizza_essence", Item.FrozenPizzaEssence],
    ["fruit_basket", Item.FruitBasket],
    ["fruit_basket_essence", Item.FruitBasketEssence],
    ["frying_pan", Item.FryingPan],
    ["frying_pan_essence", Item.FryingPanEssence],
    ["golden_carrot", Item.GoldenCarrot],
    ["golden_carrot_essence", Item.GoldenCarrotEssence],
    ["goldilocks", Item.Goldilocks],
    ["goldilocks_essence", Item.GoldilocksEssence],
    ["grave_robber", Item.GraveRobber],
    ["grave_robber_essence", Item.GraveRobberEssence],
    ["gray_pepper", Item.GrayPepper],
    ["gray_pepper_essence", Item.GrayPepperEssence],
    ["green_pepper", Item.GreenPepper],
    ["green_pepper_essence", Item.GreenPepperEssence],
    ["guillotine", Item.Guillotine],
    ["guillotine_essence", Item.GuillotineEssence],
    ["happy_hour", Item.HappyHour],
    ["happy_hour_essence", Item.HappyHourEssence],
    ["holy_water", Item.HolyWater],
    ["holy_water_essence", Item.HolyWaterEssence],
    ["horseshoe", Item.Horseshoe],
    ["horseshoe_essence", Item.HorseshoeEssence],
    ["item_missing", Item.ItemMissing],
    ["jackolantern", Item.Jackolantern],
    ["jackolantern_essence", Item.JackolanternEssence],
    ["kyle_the_kernite", Item.KyleTheKernite],
    ["kyle_the_kernite_essence", Item.KyleTheKerniteEssence],
    ["lefty_the_rabbit", Item.LeftyTheRabbit],
    ["lefty_the_rabbit_essence", Item.LeftyTheRabbitEssence],
    ["lemon", Item.Lemon],
    ["lemon_essence", Item.LemonEssence],
    ["lime_pepper", Item.LimePepper],
    ["lime_pepper_essence", Item.LimePepperEssence],
    ["lint_roller", Item.LintRoller],
    ["lint_roller_essence", Item.LintRollerEssence],
    ["lockpick", Item.Lockpick],
    ["lockpick_essence", Item.LockpickEssence],
    ["looting_glove", Item.LootingGlove],
    ["looting_glove_essence", Item.LootingGloveEssence],
    ["lucky_carrot", Item.LuckyCarrot],
    ["lucky_carrot_essence", Item.LuckyCarrotEssence],
    ["lucky_cat", Item.LuckyCat],
    ["lucky_cat_essence", Item.LuckyCatEssence],
    ["lucky_dice", Item.LuckyDice],
    ["lucky_dice_essence", Item.LuckyDiceEssence],
    ["lucky_seven", Item.LuckySeven],
    ["lucky_seven_essence", Item.LuckySevenEssence],
    ["lunchbox", Item.Lunchbox],
    ["lunchbox_essence", Item.LunchboxEssence],
    ["maxwell_the_bear", Item.MaxwellTheBear],
    ["maxwell_the_bear_essence", Item.MaxwellTheBearEssence],
    ["mining_pick", Item.MiningPick],
    ["mining_pick_essence", Item.MiningPickEssence],
    ["mobius_strip", Item.MobiusStrip],
    ["mobius_strip_essence", Item.MobiusStripEssence],
    ["ninja_and_mouse", Item.NinjaAndMouse],
    ["ninja_and_mouse_essence", Item.NinjaAndMouseEssence],
    ["nori_the_rabbit", Item.NoriTheRabbit],
    ["nori_the_rabbit_essence", Item.NoriTheRabbitEssence],
    ["oil_can", Item.OilCan],
    ["oil_can_essence", Item.OilCanEssence],
    ["oswald_the_monkey", Item.OswaldTheMonkey],
    ["oswald_the_monkey_essence", Item.OswaldTheMonkeyEssence],
    ["piggy_bank", Item.PiggyBank],
    ["piggy_bank_essence", Item.PiggyBankEssence],
    ["pink_pepper", Item.PinkPepper],
    ["pink_pepper_essence", Item.PinkPepperEssence],
    ["pizza_the_cat", Item.PizzaTheCat],
    ["pizza_the_cat_essence", Item.PizzaTheCatEssence],
    ["pool_ball", Item.PoolBall],
    ["pool_ball_essence", Item.PoolBallEssence],
    ["popsicle", Item.Popsicle],
    ["popsicle_essence", Item.PopsicleEssence],
    ["protractor", Item.Protractor],
    ["protractor_essence", Item.ProtractorEssence],
    ["purple_pepper", Item.PurplePepper],
    ["purple_pepper_essence", Item.PurplePepperEssence],
    ["quigley_the_wolf", Item.QuigleyTheWolf],
    ["quigley_the_wolf_essence", Item.QuigleyTheWolfEssence],
    ["quiver", Item.Quiver],
    ["quiver_essence", Item.QuiverEssence],
    ["rain_cloud", Item.RainCloud],
    ["rain_cloud_essence", Item.RainCloudEssence],
    ["recycling", Item.Recycling],
    ["recycling_essence", Item.RecyclingEssence],
    ["red_pepper", Item.RedPepper],
    ["red_pepper_essence", Item.RedPepperEssence],
    ["red_suits", Item.RedSuits],
    ["red_suits_essence", Item.RedSuitsEssence],
    ["reroll", Item.Reroll],
    ["reroll_essence", Item.RerollEssence],
    ["ricky_the_banana", Item.RickyTheBanana],
    ["ricky_the_banana_essence", Item.RickyTheBananaEssence],
    ["ritual_candle", Item.RitualCandle],
    ["ritual_candle_essence", Item.RitualCandleEssence],
    ["rusty_gear", Item.RustyGear],
    ["rusty_gear_essence", Item.RustyGearEssence],
    ["shattered_mirror", Item.ShatteredMirror],
    ["shattered_mirror_essence", Item.ShatteredMirrorEssence],
    ["shedding_season", Item.SheddingSeason],
    ["shedding_season_essence", Item.SheddingSeasonEssence],
    ["shrine", Item.Shrine],
    ["shrine_essence", Item.ShrineEssence],
    ["sunglasses", Item.Sunglasses],
    ["sunglasses_essence", Item.SunglassesEssence],
    ["swapping_device", Item.SwappingDevice],
    ["swapping_device_essence", Item.SwappingDeviceEssence],
    ["swear_jar", Item.SwearJar],
    ["swear_jar_essence", Item.SwearJarEssence],
    ["symbol_bomb_big", Item.SymbolBombBig],
    ["symbol_bomb_big_essence", Item.SymbolBombBigEssence],
    ["symbol_bomb_quantum", Item.SymbolBombQuantum],
    ["symbol_bomb_quantum_essence", Item.SymbolBombQuantumEssence],
    ["symbol_bomb_small", Item.SymbolBombSmall],
    ["symbol_bomb_small_essence", Item.SymbolBombSmallEssence],
    ["symbol_bomb_very_big", Item.SymbolBombVeryBig],
    ["symbol_bomb_very_big_essence", Item.SymbolBombVeryBigEssence],
    ["tax_evasion", Item.TaxEvasion],
    ["tax_evasion_essence", Item.TaxEvasionEssence],
    ["telescope", Item.Telescope],
    ["telescope_essence", Item.TelescopeEssence],
    ["time_machine", Item.TimeMachine],
    ["time_machine_essence", Item.TimeMachineEssence],
    ["treasure_map", Item.TreasureMap],
    ["treasure_map_essence", Item.TreasureMapEssence],
    ["triple_coins", Item.TripleCoins],
    ["triple_coins_essence", Item.TripleCoinsEssence],
    ["turtle_and_rabbit", Item.TurtleAndRabbit],
    ["turtle_and_rabbit_essence", Item.TurtleAndRabbitEssence],
    ["undertaker", Item.Undertaker],
    ["undertaker_essence", Item.UndertakerEssence],
    ["void_party", Item.VoidParty],
    ["void_party_essence", Item.VoidPartyEssence],
    ["void_portal", Item.VoidPortal],
    ["void_portal_essence", Item.VoidPortalEssence],
    ["wanted_poster", Item.WantedPoster],
    ["wanted_poster_essence", Item.WantedPosterEssence],
    ["watering_can", Item.WateringCan],
    ["watering_can_essence", Item.WateringCanEssence],
    ["white_pepper", Item.WhitePepper],
    ["white_pepper_essence", Item.WhitePepperEssence],
    ["x_ray_machine", Item.XRayMachine],
    ["x_ray_machine_essence", Item.XRayMachineEssence],
    ["yellow_pepper", Item.YellowPepper],
    ["yellow_pepper_essence", Item.YellowPepperEssence],
    ["zaroffs_contract", Item.ZaroffsContract],
    ["zaroffs_contract_essence", Item.ZaroffsContractEssence],
]);


export const ITEM_TO_IMG: Map<Item, string> = new Map([
    [Item.AdoptionPapers, adoption_papers],
    [Item.AdoptionPapersEssence, adoption_papers_essence],
    [Item.AncientLizardBlade, ancient_lizard_blade],
    [Item.AncientLizardBladeEssence, ancient_lizard_blade_essence],
    [Item.AnthropologyDegree, anthropology_degree],
    [Item.AnthropologyDegreeEssence, anthropology_degree_essence],
    [Item.InstantRamen, bag_of_holding],
    [Item.InstantRamenEssence, bag_of_holding_essence],
    [Item.BarrelODwarves, barrel_o_dwarves],
    [Item.BarrelODwarvesEssence, barrel_o_dwarves_essence],
    [Item.Birdhouse, birdhouse],
    [Item.BirdhouseEssence, birdhouse_essence],
    [Item.BlackCat, black_cat],
    [Item.BlackCatEssence, black_cat_essence],
    [Item.BlackPepper, black_pepper],
    [Item.BlackPepperEssence, black_pepper_essence],
    [Item.BluePepper, blue_pepper],
    [Item.BluePepperEssence, blue_pepper_essence],
    [Item.BlueSuits, blue_suits],
    [Item.BlueSuitsEssence, blue_suits_essence],
    [Item.BoosterPack, booster_pack],
    [Item.BoosterPackEssence, booster_pack_essence],
    [Item.BowlingBall, bowling_ball],
    [Item.BowlingBallEssence, bowling_ball_essence],
    [Item.BrownPepper, brown_pepper],
    [Item.BrownPepperEssence, brown_pepper_essence],
    [Item.CapsuleMachine, capsule_machine],
    [Item.CapsuleMachineEssence, capsule_machine_essence],
    [Item.CardboardBox, cardboard_box],
    [Item.CardboardBoxEssence, cardboard_box_essence],
    [Item.CheckeredFlag, checkered_flag],
    [Item.CheckeredFlagEssence, checkered_flag_essence],
    [Item.ChickenCoop, chicken_coop],
    [Item.ChickenCoopEssence, chicken_coop_essence],
    [Item.ChiliPowder, chili_powder],
    [Item.ChiliPowderEssence, chili_powder_essence],
    [Item.CleaningRag, cleaning_rag],
    [Item.CleaningRagEssence, cleaning_rag_essence],
    [Item.ClearSky, clear_sky],
    [Item.ClearSkyEssence, clear_sky_essence],
    [Item.Coffee, coffee],
    [Item.CoffeeEssence, coffee_essence],
    [Item.CoinOnAString, coin_on_a_string],
    [Item.CoinOnAStringEssence, coin_on_a_string_essence],
    [Item.ComfyPillow, comfy_pillow],
    [Item.ComfyPillowEssence, comfy_pillow_essence],
    [Item.CompostHeap, compost_heap],
    [Item.CompostHeapEssence, compost_heap_essence],
    [Item.ConveyorBelt, conveyor_belt],
    [Item.ConveyorBeltEssence, conveyor_belt_essence],
    [Item.Copycat, copycat],
    [Item.CopycatEssence, copycat_essence],
    [Item.CreditCard, credit_card],
    [Item.CreditCardEssence, credit_card_essence],
    [Item.CursedKatana, cursed_katana],
    [Item.CursedKatanaEssence, cursed_katana_essence],
    [Item.CyanPepper, cyan_pepper],
    [Item.CyanPepperEssence, cyan_pepper_essence],
    [Item.DarkHumor, dark_humor],
    [Item.DarkHumorEssence, dark_humor_essence],
    [Item.DevilsDeal, devils_deal],
    [Item.DevilsDealEssence, devils_deal_essence],
    [Item.Dishwasher, dishwasher],
    [Item.DishwasherEssence, dishwasher_essence],
    [Item.DwarvenAnvil, dwarven_anvil],
    [Item.DwarvenAnvilEssence, dwarven_anvil_essence],
    [Item.EggCarton, egg_carton],
    [Item.EggCartonEssence, egg_carton_essence],
    [Item.Fertilizer, fertilizer],
    [Item.FertilizerEssence, fertilizer_essence],
    [Item.FifthAce, fifth_ace],
    [Item.FifthAceEssence, fifth_ace_essence],
    [Item.FishBowl, fish_bowl],
    [Item.FishBowlEssence, fish_bowl_essence],
    [Item.Flush, flush],
    [Item.FlushEssence, flush_essence],
    [Item.FourLeafClover, four_leaf_clover],
    [Item.FourLeafCloverEssence, four_leaf_clover_essence],
    [Item.FrozenPizza, frozen_pizza],
    [Item.FrozenPizzaEssence, frozen_pizza_essence],
    [Item.FruitBasket, fruit_basket],
    [Item.FruitBasketEssence, fruit_basket_essence],
    [Item.FryingPan, frying_pan],
    [Item.FryingPanEssence, frying_pan_essence],
    [Item.GoldenCarrot, golden_carrot],
    [Item.GoldenCarrotEssence, golden_carrot_essence],
    [Item.Goldilocks, goldilocks],
    [Item.GoldilocksEssence, goldilocks_essence],
    [Item.GraveRobber, grave_robber],
    [Item.GraveRobberEssence, grave_robber_essence],
    [Item.GrayPepper, gray_pepper],
    [Item.GrayPepperEssence, gray_pepper_essence],
    [Item.GreenPepper, green_pepper],
    [Item.GreenPepperEssence, green_pepper_essence],
    [Item.Guillotine, guillotine],
    [Item.GuillotineEssence, guillotine_essence],
    [Item.HappyHour, happy_hour],
    [Item.HappyHourEssence, happy_hour_essence],
    [Item.HolyWater, holy_water],
    [Item.HolyWaterEssence, holy_water_essence],
    [Item.Horseshoe, horseshoe],
    [Item.HorseshoeEssence, horseshoe_essence],
    [Item.ItemMissing, item_missing],
    [Item.Jackolantern, jackolantern],
    [Item.JackolanternEssence, jackolantern_essence],
    [Item.KyleTheKernite, kyle_the_kernite],
    [Item.KyleTheKerniteEssence, kyle_the_kernite_essence],
    [Item.LeftyTheRabbit, lefty_the_rabbit],
    [Item.LeftyTheRabbitEssence, lefty_the_rabbit_essence],
    [Item.Lemon, lemon],
    [Item.LemonEssence, lemon_essence],
    [Item.LimePepper, lime_pepper],
    [Item.LimePepperEssence, lime_pepper_essence],
    [Item.LintRoller, lint_roller],
    [Item.LintRollerEssence, lint_roller_essence],
    [Item.Lockpick, lockpick],
    [Item.LockpickEssence, lockpick_essence],
    [Item.LootingGlove, looting_glove],
    [Item.LootingGloveEssence, looting_glove_essence],
    [Item.LuckyCarrot, lucky_carrot],
    [Item.LuckyCarrotEssence, lucky_carrot_essence],
    [Item.LuckyCat, lucky_cat],
    [Item.LuckyCatEssence, lucky_cat_essence],
    [Item.LuckyDice, lucky_dice],
    [Item.LuckyDiceEssence, lucky_dice_essence],
    [Item.LuckySeven, lucky_seven],
    [Item.LuckySevenEssence, lucky_seven_essence],
    [Item.Lunchbox, lunchbox],
    [Item.LunchboxEssence, lunchbox_essence],
    [Item.MaxwellTheBear, maxwell_the_bear],
    [Item.MaxwellTheBearEssence, maxwell_the_bear_essence],
    [Item.MiningPick, mining_pick],
    [Item.MiningPickEssence, mining_pick_essence],
    [Item.MobiusStrip, mobius_strip],
    [Item.MobiusStripEssence, mobius_strip_essence],
    [Item.NinjaAndMouse, ninja_and_mouse],
    [Item.NinjaAndMouseEssence, ninja_and_mouse_essence],
    [Item.NoriTheRabbit, nori_the_rabbit],
    [Item.NoriTheRabbitEssence, nori_the_rabbit_essence],
    [Item.OilCan, oil_can],
    [Item.OilCanEssence, oil_can_essence],
    [Item.OswaldTheMonkey, oswald_the_monkey],
    [Item.OswaldTheMonkeyEssence, oswald_the_monkey_essence],
    [Item.PiggyBank, piggy_bank],
    [Item.PiggyBankEssence, piggy_bank_essence],
    [Item.PinkPepper, pink_pepper],
    [Item.PinkPepperEssence, pink_pepper_essence],
    [Item.PizzaTheCat, pizza_the_cat],
    [Item.PizzaTheCatEssence, pizza_the_cat_essence],
    [Item.PoolBall, pool_ball],
    [Item.PoolBallEssence, pool_ball_essence],
    [Item.Popsicle, popsicle],
    [Item.PopsicleEssence, popsicle_essence],
    [Item.Protractor, protractor],
    [Item.ProtractorEssence, protractor_essence],
    [Item.PurplePepper, purple_pepper],
    [Item.PurplePepperEssence, purple_pepper_essence],
    [Item.QuigleyTheWolf, quigley_the_wolf],
    [Item.QuigleyTheWolfEssence, quigley_the_wolf_essence],
    [Item.Quiver, quiver],
    [Item.QuiverEssence, quiver_essence],
    [Item.RainCloud, rain_cloud],
    [Item.RainCloudEssence, rain_cloud_essence],
    [Item.Recycling, recycling],
    [Item.RecyclingEssence, recycling_essence],
    [Item.RedPepper, red_pepper],
    [Item.RedPepperEssence, red_pepper_essence],
    [Item.RedSuits, red_suits],
    [Item.RedSuitsEssence, red_suits_essence],
    [Item.Reroll, reroll],
    [Item.RerollEssence, reroll_essence],
    [Item.RickyTheBanana, ricky_the_banana],
    [Item.RickyTheBananaEssence, ricky_the_banana_essence],
    [Item.RitualCandle, ritual_candle],
    [Item.RitualCandleEssence, ritual_candle_essence],
    [Item.RustyGear, rusty_gear],
    [Item.RustyGearEssence, rusty_gear_essence],
    [Item.ShatteredMirror, shattered_mirror],
    [Item.ShatteredMirrorEssence, shattered_mirror_essence],
    [Item.SheddingSeason, shedding_season],
    [Item.SheddingSeasonEssence, shedding_season_essence],
    [Item.Shrine, shrine],
    [Item.ShrineEssence, shrine_essence],
    [Item.Sunglasses, sunglasses],
    [Item.SunglassesEssence, sunglasses_essence],
    [Item.SwappingDevice, swapping_device],
    [Item.SwappingDeviceEssence, swapping_device_essence],
    [Item.SwearJar, swear_jar],
    [Item.SwearJarEssence, swear_jar_essence],
    [Item.SymbolBombBig, symbol_bomb_big],
    [Item.SymbolBombBigEssence, symbol_bomb_big_essence],
    [Item.SymbolBombQuantum, symbol_bomb_quantum],
    [Item.SymbolBombQuantumEssence, symbol_bomb_quantum_essence],
    [Item.SymbolBombSmall, symbol_bomb_small],
    [Item.SymbolBombSmallEssence, symbol_bomb_small_essence],
    [Item.SymbolBombVeryBig, symbol_bomb_very_big],
    [Item.SymbolBombVeryBigEssence, symbol_bomb_very_big_essence],
    [Item.TaxEvasion, tax_evasion],
    [Item.TaxEvasionEssence, tax_evasion_essence],
    [Item.Telescope, telescope],
    [Item.TelescopeEssence, telescope_essence],
    [Item.TimeMachine, time_machine],
    [Item.TimeMachineEssence, time_machine_essence],
    [Item.TreasureMap, treasure_map],
    [Item.TreasureMapEssence, treasure_map_essence],
    [Item.TripleCoins, triple_coins],
    [Item.TripleCoinsEssence, triple_coins_essence],
    [Item.TurtleAndRabbit, turtle_and_rabbit],
    [Item.TurtleAndRabbitEssence, turtle_and_rabbit_essence],
    [Item.Undertaker, undertaker],
    [Item.UndertakerEssence, undertaker_essence],
    [Item.VoidParty, void_party],
    [Item.VoidPartyEssence, void_party_essence],
    [Item.VoidPortal, void_portal],
    [Item.VoidPortalEssence, void_portal_essence],
    [Item.WantedPoster, wanted_poster],
    [Item.WantedPosterEssence, wanted_poster_essence],
    [Item.WateringCan, watering_can],
    [Item.WateringCanEssence, watering_can_essence],
    [Item.WhitePepper, white_pepper],
    [Item.WhitePepperEssence, white_pepper_essence],
    [Item.XRayMachine, x_ray_machine],
    [Item.XRayMachineEssence, x_ray_machine_essence],
    [Item.YellowPepper, yellow_pepper],
    [Item.YellowPepperEssence, yellow_pepper_essence],
    [Item.ZaroffsContract, zaroffs_contract],
    [Item.ZaroffsContractEssence, zaroffs_contract_essence],
])
