// Generated by scrape_items.py
import { Item } from "../common/models/item"


const adoption_papers = require("../img/items/adoption_papers.png");
const ancient_lizard_blade = require("../img/items/ancient_lizard_blade.png");
const anthropology_degree = require("../img/items/anthropology_degree.png");
const bag_of_holding = require("../img/items/bag_of_holding.png");
const barrel_o_dwarves = require("../img/items/barrel_o_dwarves.png");
const birdhouse = require("../img/items/birdhouse.png");
const black_cat = require("../img/items/black_cat.png");
const black_pepper = require("../img/items/black_pepper.png");
const blue_pepper = require("../img/items/blue_pepper.png");
const blue_suits = require("../img/items/blue_suits.png");
const booster_pack = require("../img/items/booster_pack.png");
const bowling_ball = require("../img/items/bowling_ball.png");
const brown_pepper = require("../img/items/brown_pepper.png");
const capsule_machine = require("../img/items/capsule_machine.png");
const cardboard_box = require("../img/items/cardboard_box.png");
const checkered_flag = require("../img/items/checkered_flag.png");
const chicken_coop = require("../img/items/chicken_coop.png");
const chili_powder = require("../img/items/chili_powder.png");
const cleaning_rag = require("../img/items/cleaning_rag.png");
const clear_sky = require("../img/items/clear_sky.png");
const coffee = require("../img/items/coffee.png");
const coin_on_a_string = require("../img/items/coin_on_a_string.png");
const comfy_pillow = require("../img/items/comfy_pillow.png");
const compost_heap = require("../img/items/compost_heap.png");
const conveyor_belt = require("../img/items/conveyor_belt.png");
const copycat = require("../img/items/copycat.png");
const credit_card = require("../img/items/credit_card.png");
const cursed_katana = require("../img/items/cursed_katana.png");
const cyan_pepper = require("../img/items/cyan_pepper.png");
const dark_humor = require("../img/items/dark_humor.png");
const devils_deal = require("../img/items/devils_deal.png");
const dishwasher = require("../img/items/dishwasher.png");
const dwarven_anvil = require("../img/items/dwarven_anvil.png");
const egg_carton = require("../img/items/egg_carton.png");
const fertilizer = require("../img/items/fertilizer.png");
const fifth_ace = require("../img/items/fifth_ace.png");
const fish_bowl = require("../img/items/fish_bowl.png");
const flush = require("../img/items/flush.png");
const four_leaf_clover = require("../img/items/four_leaf_clover.png");
const frozen_pizza = require("../img/items/frozen_pizza.png");
const fruit_basket = require("../img/items/fruit_basket.png");
const frying_pan = require("../img/items/frying_pan.png");
const golden_carrot = require("../img/items/golden_carrot.png");
const goldilocks = require("../img/items/goldilocks.png");
const grave_robber = require("../img/items/grave_robber.png");
const gray_pepper = require("../img/items/gray_pepper.png");
const green_pepper = require("../img/items/green_pepper.png");
const guillotine = require("../img/items/guillotine.png");
const happy_hour = require("../img/items/happy_hour.png");
const holy_water = require("../img/items/holy_water.png");
const horseshoe = require("../img/items/horseshoe.png");
const item_missing = require("../img/items/item_missing.png");
const jackolantern = require("../img/items/jackolantern.png");
const kyle_the_kernite = require("../img/items/kyle_the_kernite.png");
const lefty_the_rabbit = require("../img/items/lefty_the_rabbit.png");
const lemon = require("../img/items/lemon.png");
const lime_pepper = require("../img/items/lime_pepper.png");
const lint_roller = require("../img/items/lint_roller.png");
const lockpick = require("../img/items/lockpick.png");
const looting_glove = require("../img/items/looting_glove.png");
const lucky_carrot = require("../img/items/lucky_carrot.png");
const lucky_cat = require("../img/items/lucky_cat.png");
const lucky_dice = require("../img/items/lucky_dice.png");
const lucky_seven = require("../img/items/lucky_seven.png");
const lunchbox = require("../img/items/lunchbox.png");
const maxwell_the_bear = require("../img/items/maxwell_the_bear.png");
const mining_pick = require("../img/items/mining_pick.png");
const mobius_strip = require("../img/items/mobius_strip.png");
const ninja_and_mouse = require("../img/items/ninja_and_mouse.png");
const nori_the_rabbit = require("../img/items/nori_the_rabbit.png");
const oil_can = require("../img/items/oil_can.png");
const oswald_the_monkey = require("../img/items/oswald_the_monkey.png");
const piggy_bank = require("../img/items/piggy_bank.png");
const pink_pepper = require("../img/items/pink_pepper.png");
const pizza_the_cat = require("../img/items/pizza_the_cat.png");
const pool_ball = require("../img/items/pool_ball.png");
const popsicle = require("../img/items/popsicle.png");
const protractor = require("../img/items/protractor.png");
const purple_pepper = require("../img/items/purple_pepper.png");
const quigley_the_wolf = require("../img/items/quigley_the_wolf.png");
const quiver = require("../img/items/quiver.png");
const rain_cloud = require("../img/items/rain_cloud.png");
const recycling = require("../img/items/recycling.png");
const red_pepper = require("../img/items/red_pepper.png");
const red_suits = require("../img/items/red_suits.png");
const reroll = require("../img/items/reroll.png");
const ricky_the_banana = require("../img/items/ricky_the_banana.png");
const ritual_candle = require("../img/items/ritual_candle.png");
const rusty_gear = require("../img/items/rusty_gear.png");
const shattered_mirror = require("../img/items/shattered_mirror.png");
const shedding_season = require("../img/items/shedding_season.png");
const shrine = require("../img/items/shrine.png");
const sunglasses = require("../img/items/sunglasses.png");
const swapping_device = require("../img/items/swapping_device.png");
const swear_jar = require("../img/items/swear_jar.png");
const symbol_bomb_big = require("../img/items/symbol_bomb_big.png");
const symbol_bomb_quantum = require("../img/items/symbol_bomb_quantum.png");
const symbol_bomb_small = require("../img/items/symbol_bomb_small.png");
const symbol_bomb_very_big = require("../img/items/symbol_bomb_very_big.png");
const tax_evasion = require("../img/items/tax_evasion.png");
const telescope = require("../img/items/telescope.png");
const time_machine = require("../img/items/time_machine.png");
const treasure_map = require("../img/items/treasure_map.png");
const triple_coins = require("../img/items/triple_coins.png");
const turtle_and_rabbit = require("../img/items/turtle_and_rabbit.png");
const undertaker = require("../img/items/undertaker.png");
const void_party = require("../img/items/void_party.png");
const void_portal = require("../img/items/void_portal.png");
const wanted_poster = require("../img/items/wanted_poster.png");
const watering_can = require("../img/items/watering_can.png");
const white_pepper = require("../img/items/white_pepper.png");
const x_ray_machine = require("../img/items/x_ray_machine.png");
const yellow_pepper = require("../img/items/yellow_pepper.png");
const zaroffs_contract = require("../img/items/zaroffs_contract.png");



export const IIDToItem = (iid: string): Item => {
    return IID_TO_ITEM.get(iid) ?? Item.ItemMissing;
}

// Internal ID to item mapping
export const IID_TO_ITEM: Map<string, Item> = new Map([
    ["adoption_papers", Item.AdoptionPapers],
    ["ancient_lizard_blade", Item.AncientLizardBlade],
    ["anthropology_degree", Item.AnthropologyDegree],
    ["bag_of_holding", Item.BagOfHolding],
    ["barrel_o_dwarves", Item.BarrelODwarves],
    ["birdhouse", Item.Birdhouse],
    ["black_cat", Item.BlackCat],
    ["black_pepper", Item.BlackPepper],
    ["blue_pepper", Item.BluePepper],
    ["blue_suits", Item.BlueSuits],
    ["booster_pack", Item.BoosterPack],
    ["bowling_ball", Item.BowlingBall],
    ["brown_pepper", Item.BrownPepper],
    ["capsule_machine", Item.CapsuleMachine],
    ["cardboard_box", Item.CardboardBox],
    ["checkered_flag", Item.CheckeredFlag],
    ["chicken_coop", Item.ChickenCoop],
    ["chili_powder", Item.ChiliPowder],
    ["cleaning_rag", Item.CleaningRag],
    ["clear_sky", Item.ClearSky],
    ["coffee", Item.Coffee],
    ["coin_on_a_string", Item.CoinOnAString],
    ["comfy_pillow", Item.ComfyPillow],
    ["compost_heap", Item.CompostHeap],
    ["conveyor_belt", Item.ConveyorBelt],
    ["copycat", Item.Copycat],
    ["credit_card", Item.CreditCard],
    ["cursed_katana", Item.CursedKatana],
    ["cyan_pepper", Item.CyanPepper],
    ["dark_humor", Item.DarkHumor],
    ["devils_deal", Item.DevilsDeal],
    ["dishwasher", Item.Dishwasher],
    ["dwarven_anvil", Item.DwarvenAnvil],
    ["egg_carton", Item.EggCarton],
    ["fertilizer", Item.Fertilizer],
    ["fifth_ace", Item.FifthAce],
    ["fish_bowl", Item.FishBowl],
    ["flush", Item.Flush],
    ["four_leaf_clover", Item.FourLeafClover],
    ["frozen_pizza", Item.FrozenPizza],
    ["fruit_basket", Item.FruitBasket],
    ["frying_pan", Item.FryingPan],
    ["golden_carrot", Item.GoldenCarrot],
    ["goldilocks", Item.Goldilocks],
    ["grave_robber", Item.GraveRobber],
    ["gray_pepper", Item.GrayPepper],
    ["green_pepper", Item.GreenPepper],
    ["guillotine", Item.Guillotine],
    ["happy_hour", Item.HappyHour],
    ["holy_water", Item.HolyWater],
    ["horseshoe", Item.Horseshoe],
    ["item_missing", Item.ItemMissing],
    ["jackolantern", Item.Jackolantern],
    ["kyle_the_kernite", Item.KyleTheKernite],
    ["lefty_the_rabbit", Item.LeftyTheRabbit],
    ["lemon", Item.Lemon],
    ["lime_pepper", Item.LimePepper],
    ["lint_roller", Item.LintRoller],
    ["lockpick", Item.Lockpick],
    ["looting_glove", Item.LootingGlove],
    ["lucky_carrot", Item.LuckyCarrot],
    ["lucky_cat", Item.LuckyCat],
    ["lucky_dice", Item.LuckyDice],
    ["lucky_seven", Item.LuckySeven],
    ["lunchbox", Item.Lunchbox],
    ["maxwell_the_bear", Item.MaxwellTheBear],
    ["mining_pick", Item.MiningPick],
    ["mobius_strip", Item.MobiusStrip],
    ["ninja_and_mouse", Item.NinjaAndMouse],
    ["nori_the_rabbit", Item.NoriTheRabbit],
    ["oil_can", Item.OilCan],
    ["oswald_the_monkey", Item.OswaldTheMonkey],
    ["piggy_bank", Item.PiggyBank],
    ["pink_pepper", Item.PinkPepper],
    ["pizza_the_cat", Item.PizzaTheCat],
    ["pool_ball", Item.PoolBall],
    ["popsicle", Item.Popsicle],
    ["protractor", Item.Protractor],
    ["purple_pepper", Item.PurplePepper],
    ["quigley_the_wolf", Item.QuigleyTheWolf],
    ["quiver", Item.Quiver],
    ["rain_cloud", Item.RainCloud],
    ["recycling", Item.Recycling],
    ["red_pepper", Item.RedPepper],
    ["red_suits", Item.RedSuits],
    ["reroll", Item.Reroll],
    ["ricky_the_banana", Item.RickyTheBanana],
    ["ritual_candle", Item.RitualCandle],
    ["rusty_gear", Item.RustyGear],
    ["shattered_mirror", Item.ShatteredMirror],
    ["shedding_season", Item.SheddingSeason],
    ["shrine", Item.Shrine],
    ["sunglasses", Item.Sunglasses],
    ["swapping_device", Item.SwappingDevice],
    ["swear_jar", Item.SwearJar],
    ["symbol_bomb_big", Item.SymbolBombBig],
    ["symbol_bomb_quantum", Item.SymbolBombQuantum],
    ["symbol_bomb_small", Item.SymbolBombSmall],
    ["symbol_bomb_very_big", Item.SymbolBombVeryBig],
    ["tax_evasion", Item.TaxEvasion],
    ["telescope", Item.Telescope],
    ["time_machine", Item.TimeMachine],
    ["treasure_map", Item.TreasureMap],
    ["triple_coins", Item.TripleCoins],
    ["turtle_and_rabbit", Item.TurtleAndRabbit],
    ["undertaker", Item.Undertaker],
    ["void_party", Item.VoidParty],
    ["void_portal", Item.VoidPortal],
    ["wanted_poster", Item.WantedPoster],
    ["watering_can", Item.WateringCan],
    ["white_pepper", Item.WhitePepper],
    ["x_ray_machine", Item.XRayMachine],
    ["yellow_pepper", Item.YellowPepper],
    ["zaroffs_contract", Item.ZaroffsContract],
]);


export const ITEM_TO_IMG: Map<Item, string> = new Map([
    [Item.AdoptionPapers, adoption_papers],
    [Item.AncientLizardBlade, ancient_lizard_blade],
    [Item.AnthropologyDegree, anthropology_degree],
    [Item.BagOfHolding, bag_of_holding],
    [Item.BarrelODwarves, barrel_o_dwarves],
    [Item.Birdhouse, birdhouse],
    [Item.BlackCat, black_cat],
    [Item.BlackPepper, black_pepper],
    [Item.BluePepper, blue_pepper],
    [Item.BlueSuits, blue_suits],
    [Item.BoosterPack, booster_pack],
    [Item.BowlingBall, bowling_ball],
    [Item.BrownPepper, brown_pepper],
    [Item.CapsuleMachine, capsule_machine],
    [Item.CardboardBox, cardboard_box],
    [Item.CheckeredFlag, checkered_flag],
    [Item.ChickenCoop, chicken_coop],
    [Item.ChiliPowder, chili_powder],
    [Item.CleaningRag, cleaning_rag],
    [Item.ClearSky, clear_sky],
    [Item.Coffee, coffee],
    [Item.CoinOnAString, coin_on_a_string],
    [Item.ComfyPillow, comfy_pillow],
    [Item.CompostHeap, compost_heap],
    [Item.ConveyorBelt, conveyor_belt],
    [Item.Copycat, copycat],
    [Item.CreditCard, credit_card],
    [Item.CursedKatana, cursed_katana],
    [Item.CyanPepper, cyan_pepper],
    [Item.DarkHumor, dark_humor],
    [Item.DevilsDeal, devils_deal],
    [Item.Dishwasher, dishwasher],
    [Item.DwarvenAnvil, dwarven_anvil],
    [Item.EggCarton, egg_carton],
    [Item.Fertilizer, fertilizer],
    [Item.FifthAce, fifth_ace],
    [Item.FishBowl, fish_bowl],
    [Item.Flush, flush],
    [Item.FourLeafClover, four_leaf_clover],
    [Item.FrozenPizza, frozen_pizza],
    [Item.FruitBasket, fruit_basket],
    [Item.FryingPan, frying_pan],
    [Item.GoldenCarrot, golden_carrot],
    [Item.Goldilocks, goldilocks],
    [Item.GraveRobber, grave_robber],
    [Item.GrayPepper, gray_pepper],
    [Item.GreenPepper, green_pepper],
    [Item.Guillotine, guillotine],
    [Item.HappyHour, happy_hour],
    [Item.HolyWater, holy_water],
    [Item.Horseshoe, horseshoe],
    [Item.ItemMissing, item_missing],
    [Item.Jackolantern, jackolantern],
    [Item.KyleTheKernite, kyle_the_kernite],
    [Item.LeftyTheRabbit, lefty_the_rabbit],
    [Item.Lemon, lemon],
    [Item.LimePepper, lime_pepper],
    [Item.LintRoller, lint_roller],
    [Item.Lockpick, lockpick],
    [Item.LootingGlove, looting_glove],
    [Item.LuckyCarrot, lucky_carrot],
    [Item.LuckyCat, lucky_cat],
    [Item.LuckyDice, lucky_dice],
    [Item.LuckySeven, lucky_seven],
    [Item.Lunchbox, lunchbox],
    [Item.MaxwellTheBear, maxwell_the_bear],
    [Item.MiningPick, mining_pick],
    [Item.MobiusStrip, mobius_strip],
    [Item.NinjaAndMouse, ninja_and_mouse],
    [Item.NoriTheRabbit, nori_the_rabbit],
    [Item.OilCan, oil_can],
    [Item.OswaldTheMonkey, oswald_the_monkey],
    [Item.PiggyBank, piggy_bank],
    [Item.PinkPepper, pink_pepper],
    [Item.PizzaTheCat, pizza_the_cat],
    [Item.PoolBall, pool_ball],
    [Item.Popsicle, popsicle],
    [Item.Protractor, protractor],
    [Item.PurplePepper, purple_pepper],
    [Item.QuigleyTheWolf, quigley_the_wolf],
    [Item.Quiver, quiver],
    [Item.RainCloud, rain_cloud],
    [Item.Recycling, recycling],
    [Item.RedPepper, red_pepper],
    [Item.RedSuits, red_suits],
    [Item.Reroll, reroll],
    [Item.RickyTheBanana, ricky_the_banana],
    [Item.RitualCandle, ritual_candle],
    [Item.RustyGear, rusty_gear],
    [Item.ShatteredMirror, shattered_mirror],
    [Item.SheddingSeason, shedding_season],
    [Item.Shrine, shrine],
    [Item.Sunglasses, sunglasses],
    [Item.SwappingDevice, swapping_device],
    [Item.SwearJar, swear_jar],
    [Item.SymbolBombBig, symbol_bomb_big],
    [Item.SymbolBombQuantum, symbol_bomb_quantum],
    [Item.SymbolBombSmall, symbol_bomb_small],
    [Item.SymbolBombVeryBig, symbol_bomb_very_big],
    [Item.TaxEvasion, tax_evasion],
    [Item.Telescope, telescope],
    [Item.TimeMachine, time_machine],
    [Item.TreasureMap, treasure_map],
    [Item.TripleCoins, triple_coins],
    [Item.TurtleAndRabbit, turtle_and_rabbit],
    [Item.Undertaker, undertaker],
    [Item.VoidParty, void_party],
    [Item.VoidPortal, void_portal],
    [Item.WantedPoster, wanted_poster],
    [Item.WateringCan, watering_can],
    [Item.WhitePepper, white_pepper],
    [Item.XRayMachine, x_ray_machine],
    [Item.YellowPepper, yellow_pepper],
    [Item.ZaroffsContract, zaroffs_contract],
])
